confirm-before-quit = true
scrollback-history-limit = 0
enable-scroll-bar = false
line-height = 1.12

[bell]
audio = true
visual = true

[effects]
trail-cursor = true

[mars.appearance]
preset = "dark"

[window]
width = 960
height = 620
decorations = "Disabled"
opacity = 0.78
opacity-cells = false

[panel]
margin = [0.0]
padding = [0.0]
border-width = 0.0

[fonts]
family = "JetBrains Mono"
size = 16.0
additional-dirs = [
  "@jetbrainsMonoDir@",
  "@symbolsNerdDir@",
  "@notoSymbolsDir@",
  "@notoEmojiDir@",
]
symbol-map = [
  { start = "E000", end = "F900", font-family = "Symbols Nerd Font Mono" },
  { start = "F0000", end = "F3000", font-family = "Symbols Nerd Font Mono" },
  { start = "1F5B0", end = "1F5C0", font-family = "Noto Sans Symbols2" },
  { start = "2600", end = "276F", font-family = "Noto Color Emoji" },
  { start = "1F000", end = "1F5B0", font-family = "Noto Color Emoji" },
  { start = "1F5C0", end = "1FB00", font-family = "Noto Color Emoji" },
]

[navigation]
mode = "Plain"
