# Contract check for the Codex config materializer (YZXCONV-004)
#
# Proves:
#   1. the reviewed input agent_configs/codex/config.toml.src exists, parses
#      as TOML, and contains no retired-workspace or profile-bypassing paths
#   2. materialization is deterministic: same input -> byte-identical output
#   3. the materialized output is parseable TOML carrying the generated marker
#   4. the materializer fails closed on retired workspace mirrors, raw
#      /nix/store pins, Nix profile-generation pins, and invalid TOML

def fail [message: string] {
    print --stderr $"codex materializer contract: ($message)"
    exit 1
}

def expect-reject [materializer: path, workdir: path, label: string, content: string] {
    let src = ($workdir | path join $"reject-($label).toml.src")
    $content | save --force --raw $src
    let out = ($workdir | path join $"reject-($label).toml")
    let result = (do { ^$nu.current-exe $materializer $src $out } | complete)
    if $result.exit_code == 0 {
        fail $"materializer accepted forbidden input: ($label)"
    }
    if ($out | path exists) {
        fail $"materializer wrote output despite rejecting input: ($label)"
    }
}

def main [root: path] {
    let materializer = ($root | path join "nushell/scripts/materialize_codex_config.nu")
    let repo_src = ($root | path join "agent_configs/codex/config.toml.src")
    if not ($materializer | path exists) {
        fail $"materializer missing: ($materializer)"
    }
    if not ($repo_src | path exists) {
        fail $"reviewed input missing: ($repo_src)"
    }

    let raw = (open --raw $repo_src)
    try { $raw | from toml | ignore } catch {
        fail "reviewed input is not valid TOML"
    }
    let forbidden = [
        "/home/flexnetos/FlexNetOS"
        "/nix/store/"
        "/nix/var/nix/profiles/"
        ".local/state/nix/profiles/profile-"
    ]
    for pattern in $forbidden {
        if ($raw | str contains $pattern) {
            fail $"reviewed input contains forbidden path ($pattern)"
        }
    }

    let workdir = (mktemp --directory --tmpdir "codex-materializer-check.XXXXXX")
    let out_a = ($workdir | path join "a" "config.toml")
    let out_b = ($workdir | path join "b" "config.toml")
    for out in [$out_a $out_b] {
        let result = (do { ^$nu.current-exe $materializer $repo_src $out } | complete)
        if $result.exit_code != 0 {
            fail $"materializer failed on reviewed input: ($result.stderr)"
        }
    }
    let hash_a = (open --raw $out_a | hash sha256)
    let hash_b = (open --raw $out_b | hash sha256)
    if $hash_a != $hash_b {
        fail $"non-deterministic output: ($hash_a) vs ($hash_b)"
    }

    let rendered = (open --raw $out_a)
    try { $rendered | from toml | ignore } catch {
        fail "materialized output is not valid TOML"
    }
    if not ($rendered | str contains "GENERATED by yazelix codex config materializer") {
        fail "materialized output missing generated marker"
    }

    expect-reject $materializer $workdir "retired-workspace" ('[projects."/home/flexnetos/FlexNetOS"]' + "\ntrust_level = \"trusted\"\n")
    expect-reject $materializer $workdir "raw-store-pin" ("[mcp_servers.icm]\ncommand = \"/nix/store/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-icm-0.0.1/bin/icm\"\n")
    expect-reject $materializer $workdir "system-profile-pin" ("[mcp_servers.icm]\ncommand = \"/nix/var/nix/profiles/default/bin/icm\"\n")
    expect-reject $materializer $workdir "user-profile-generation-pin" ("[mcp_servers.icm]\ncommand = \"/home/flexnetos/.local/state/nix/profiles/profile-4-link/bin/icm\"\n")
    expect-reject $materializer $workdir "invalid-toml" "[unterminated\n"

    let missing = (do { ^$nu.current-exe $materializer ($workdir | path join "does-not-exist.toml.src") ($workdir | path join "never.toml") } | complete)
    if $missing.exit_code == 0 {
        fail "materializer accepted a missing input path"
    }

    print "ok codex config materializer: deterministic, parseable, fail-closed"
}
