#!/bin/zsh
# Yazelix-managed Zsh startup. User hook: ~/.config/yazelix/shell_zsh.zsh
# This file is part of Yazelix and should be persisted in the repository.

YAZELIX_RUNTIME_DIR="$(cd "$(dirname "${(%):-%N}")/../.." && pwd)"

# Define the directory where Yazelix generates individual initializer scripts.
# Using XDG-compliant state directory (not config directory)
YAZELIX_ZSH_INITIALIZERS_DIR="$HOME/.local/share/yazelix/initializers/zsh"

# Prefer the aggregate initializer if present (generated by Yazelix)
if [[ -f "$YAZELIX_ZSH_INITIALIZERS_DIR/yazelix_init.zsh" && -s "$YAZELIX_ZSH_INITIALIZERS_DIR/yazelix_init.zsh" ]]; then
  source "$YAZELIX_ZSH_INITIALIZERS_DIR/yazelix_init.zsh"
else
  # Source individual initializers if they exist and are non-empty.
  if [[ -f "$YAZELIX_ZSH_INITIALIZERS_DIR/starship_init.zsh" && -s "$YAZELIX_ZSH_INITIALIZERS_DIR/starship_init.zsh" ]]; then
    source "$YAZELIX_ZSH_INITIALIZERS_DIR/starship_init.zsh"
  fi

  if [[ -f "$YAZELIX_ZSH_INITIALIZERS_DIR/zoxide_init.zsh" && -s "$YAZELIX_ZSH_INITIALIZERS_DIR/zoxide_init.zsh" ]]; then
    source "$YAZELIX_ZSH_INITIALIZERS_DIR/zoxide_init.zsh"
  fi

  # mise_init.zsh is generated conditionally by the shellHook.
  # Source it if it exists and is non-empty.
  if [[ -f "$YAZELIX_ZSH_INITIALIZERS_DIR/mise_init.zsh" && -s "$YAZELIX_ZSH_INITIALIZERS_DIR/mise_init.zsh" ]]; then
    source "$YAZELIX_ZSH_INITIALIZERS_DIR/mise_init.zsh"
  fi

  # carapace_init.zsh for completion support
  if [[ -f "$YAZELIX_ZSH_INITIALIZERS_DIR/carapace_init.zsh" && -s "$YAZELIX_ZSH_INITIALIZERS_DIR/carapace_init.zsh" ]]; then
    source "$YAZELIX_ZSH_INITIALIZERS_DIR/carapace_init.zsh"
  fi
fi

# Yazelix Aliases for Zsh
alias yazelix="sh $YAZELIX_RUNTIME_DIR/shells/posix/yzx_cli.sh launch"
alias lg='lazygit'

# Note: yzx command is defined in ~/.zshrc (via v3 hooks) and is always available

# Helix function (ensure runtime is set correctly)
hx() {
    # Ensure helix config directory exists
    local helix_config_dir="$HOME/.config/helix"
    if [[ ! -d "$helix_config_dir" ]]; then
        mkdir -p "$helix_config_dir"
    fi

    # Best-effort HELIX_RUNTIME export for environments that still expect it.
    # Helix can usually resolve its runtime on its own, so this is only a fallback.
    if [[ -z "$HELIX_RUNTIME" ]]; then
        # Fallback: try to find runtime from helix binary
        local helix_path=$(which hx 2>/dev/null)
        if [[ -n "$helix_path" ]]; then
            local runtime_path=$(dirname "$(dirname "$helix_path")")/share/helix/runtime
            if [[ -d "$runtime_path" ]]; then
                export HELIX_RUNTIME="$runtime_path"
            fi
        fi
    fi

    command hx "$@"
}

# Add other Zsh-specific aliases or functions for Yazelix here if needed.
# For example, you could move environment variable exports specific to Zsh sessions here:
# export SOME_ZSH_SPECIFIC_VAR="value"

if [[ -n "${YAZELIX_CONFIG_DIR:-}" ]]; then
  yazelix_zsh_user_hook="$YAZELIX_CONFIG_DIR/shell_zsh.zsh"
else
  yazelix_zsh_user_hook="$HOME/.config/yazelix/shell_zsh.zsh"
fi
if [[ -f "$yazelix_zsh_user_hook" && -s "$yazelix_zsh_user_hook" ]]; then
  source "$yazelix_zsh_user_hook"
fi

# Ensure this script doesn't produce output unless it's an error,
# as it's sourced by .zshrc.
