theme = "ayu_evolve"

[editor]
bufferline = "always"
color-modes = true
cursorline = true

[keys.normal]
A-r = ':sh yzn reveal "%{buffer_name}"'
C-r = [
  ":config-reload",
  ":reload",
]

[editor.file-picker]
hidden = true
