#!/bin/sh
set -eu

SCRIPT_PATH="$0"
if [ -L "$SCRIPT_PATH" ]; then
  LINK_TARGET="$(readlink "$SCRIPT_PATH")"
  case "$LINK_TARGET" in
    /*) SCRIPT_PATH="$LINK_TARGET" ;;
    *) SCRIPT_PATH="$(dirname "$SCRIPT_PATH")/$LINK_TARGET" ;;
  esac
fi

runtime_dir="$(cd "$(dirname "$SCRIPT_PATH")/../.." && pwd)"
runtime_env_script="$runtime_dir/shells/posix/runtime_env.sh"
managed_config="$runtime_dir/nushell/config/config.nu"
stack_prompt_guard="$runtime_dir/nushell/config/stack_prompt_guard.nu"

if [ ! -f "$runtime_env_script" ]; then
  printf '%s\n' "Error: missing Yazelix runtime env helper: $runtime_env_script" >&2
  exit 1
fi

if [ ! -f "$managed_config" ]; then
  printf '%s\n' "Error: missing managed Nushell config: $managed_config" >&2
  exit 1
fi

if [ ! -f "$stack_prompt_guard" ]; then
  printf '%s\n' "Error: missing managed Nushell stack prompt guard: $stack_prompt_guard" >&2
  exit 1
fi

export YAZELIX_BOOTSTRAP_RUNTIME_DIR="$runtime_dir"
. "$runtime_env_script"
unset YAZELIX_BOOTSTRAP_RUNTIME_DIR
scrub_yazelix_workspace_child_gui_env

nu_string_literal() {
  path="$1"
  case "$path" in
    *'
'*)
      printf '%s\n' "Error: cannot source Nushell config path containing a newline: $path" >&2
      exit 1
      ;;
  esac

  printf '%s\n' "$path" | sed 's/\\/\\\\/g; s/"/\\"/g'
}

generated_config_dir="$YAZELIX_STATE_DIR/generated/nushell"
generated_config="$generated_config_dir/config.nu"
user_config="$YAZELIX_CONFIG_DIR/shell_nu.nu"

mkdir -p "$generated_config_dir"

# Nushell requires `source` paths to be parse-time constants, so the POSIX
# wrapper resolves the XDG-aware paths and writes a concrete config per launch.
managed_config_literal="$(nu_string_literal "$managed_config")"
stack_prompt_guard_literal="$(nu_string_literal "$stack_prompt_guard")"
tmp_generated_config="$generated_config.tmp.$$"
{
  printf '%s\n' "# Generated by Yazelix. Do not edit."
  printf 'source "%s"\n' "$managed_config_literal"
  if [ -f "$user_config" ]; then
    user_config_literal="$(nu_string_literal "$user_config")"
    printf 'source "%s"\n' "$user_config_literal"
  fi
  printf 'source "%s"\n' "$stack_prompt_guard_literal"
} >"$tmp_generated_config"
mv "$tmp_generated_config" "$generated_config"

exec "$YAZELIX_NU_BIN" --login --env-config /dev/null --config "$generated_config" "$@"
