# Yazelix Fish Configuration
# This file is sourced by ~/.config/fish/config.fish

set -l YAZELIX_RUNTIME_DIR (path normalize (path dirname (status filename))/../..)

# Source Helix mode detection using Nushell (essential dependency)
if test -z $YAZELIX_HELIX_MODE
    eval (nu -c "use \"$YAZELIX_RUNTIME_DIR/nushell/scripts/utils/helix_mode.nu\" export_helix_env; export_helix_env")
end

# Source generated initializers if they exist
# Using XDG-compliant state directory (not config directory)
set -l FISH_INITIALIZERS_DIR "$HOME/.local/share/yazelix/initializers/fish"

# Prefer the aggregate initializer if present (generated by Yazelix)
if test -f "$FISH_INITIALIZERS_DIR/yazelix_init.fish"
    source "$FISH_INITIALIZERS_DIR/yazelix_init.fish"
else
    # Source each initializer if it exists
    for file in $FISH_INITIALIZERS_DIR/*.fish
        if test -f $file
            source $file
        end
    end
end

# Yazelix aliases
alias yazelix="nu $YAZELIX_RUNTIME_DIR/nushell/scripts/core/launch_yazelix.nu"
alias lg='lazygit'

# Note: yzx command is defined in ~/.config/fish/config.fish (via v3 hooks) and is always available

# Helix function (ensure runtime is set correctly)
function hx --description "Helix editor with Yazelix mode support"
    # Ensure helix config directory exists
    set -l helix_config_dir "$HOME/.config/helix"
    if not test -d $helix_config_dir
        mkdir -p $helix_config_dir
    end

    # Best-effort HELIX_RUNTIME export for environments that still expect it.
    # Helix can usually resolve its runtime on its own, so this is only a fallback.
    if test -z $HELIX_RUNTIME
        # Fallback: try to find runtime from helix binary
        set -l helix_path (which hx 2>/dev/null)
        if test -n $helix_path
            set -l runtime_path (dirname (dirname $helix_path))/share/helix/runtime
            if test -d $runtime_path
                set -gx HELIX_RUNTIME $runtime_path
            end
        end
    end

    command hx $argv
end

set -l fish_user_hook_dir "$HOME/.config/yazelix/user_configs/shells"
if set -q YAZELIX_USER_SHELL_HOOK_DIR; and test -n "$YAZELIX_USER_SHELL_HOOK_DIR"
    set fish_user_hook_dir "$YAZELIX_USER_SHELL_HOOK_DIR"
else if test -n "$YAZELIX_CONFIG_DIR"
    set fish_user_hook_dir "$YAZELIX_CONFIG_DIR/user_configs/shells"
end
set -l YAZELIX_FISH_USER_HOOK "$fish_user_hook_dir/fish.fish"
if test -f "$YAZELIX_FISH_USER_HOOK"
    if test -s "$YAZELIX_FISH_USER_HOOK"
        source "$YAZELIX_FISH_USER_HOOK"
    end
end
