#!/usr/bin/env nu
# Development helper commands for maintainers

use ../utils/terminal_configs.nu generate_all_terminal_configs
use ../utils/common.nu [
    get_yazelix_state_dir
    resolve_yazelix_nu_bin
]
use ../utils/repo_checkout.nu [require_yazelix_repo_root]
use ../utils/dev_issue_sync.nu run_dev_issue_sync
use ../utils/dev_plugin_build.nu [build_pane_orchestrator_wasm build_popup_plugin_wasm]
use ../utils/dev_bump_workflow.nu perform_version_bump
use ../utils/dev_update_workflow.nu run_dev_update_workflow
use ../utils/startup_profile.nu [
    create_startup_profile_run
    load_startup_profile_report
    render_startup_profile_summary
]

# Development and maintainer commands
export def "yzx dev" [] {
    print "Run 'yzx dev --help' to see available maintainer subcommands"
}

export def "yzx dev update" [
    --yes      # Skip confirmation prompt
    --no-canary  # Skip canary refresh/build checks after updating devenv.lock
    --activate: string = ""  # Required unless --canary-only: installer, home_manager, or none
    --home-manager-dir: string = "~/.config/home-manager"  # Home Manager flake directory used when --activate home_manager
    --home-manager-input: string = "yazelix-hm"  # Home Manager flake input name to refresh before switch
    --home-manager-attr: string = ""  # Optional Home Manager flake output attribute appended as #attr during switch
    --canary-only  # Run canary checks without updating devenv.lock or syncing pins
    --canaries: list<string> = []  # Canary subset: default, maximal
] {
    run_dev_update_workflow $yes $no_canary $activate $home_manager_dir $home_manager_input $home_manager_attr $canary_only $canaries
}

export def "yzx dev bump" [
    version: string  # Version tag to release, for example v14
] {
    let result = (perform_version_bump (require_yazelix_repo_root) $version)
    print $"✅ Bumped Yazelix from ($result.previous_version) to ($result.target_version)"
    print $"   commit: ($result.commit_sha)"
    print $"   tag: ($result.tag)"
}

export def "yzx dev sync_terminal_configs" [] {
    let yazelix_dir = require_yazelix_repo_root
    let config_root = ($yazelix_dir | path join "configs/terminal_emulators")
    let generated_root = "~/.local/share/yazelix/configs/terminal_emulators" | path expand
    let terminal_snapshot_override = (^mktemp /tmp/yazelix_terminal_snapshot_sync_XXXXXX.toml | str trim)

    if not ($config_root | path exists) {
        print $"❌ Configs directory not found: ($config_root)"
        exit 1
    }

    let default_config = ($yazelix_dir | path join "yazelix_default.toml")
    if not ($default_config | path exists) {
        print $"❌ Default config not found: ($default_config)"
        exit 1
    }

    print "Generating terminal configs from defaults..."
    "[terminal]\nterminals = [\"ghostty\", \"wezterm\", \"kitty\", \"alacritty\", \"foot\"]\n" | save --force --raw $terminal_snapshot_override

    with-env {YAZELIX_CONFIG_OVERRIDE: $terminal_snapshot_override} {
        generate_all_terminal_configs
    }
    rm -f $terminal_snapshot_override

    let generated_at = (date now | format date "%Y-%m-%d %H:%M:%S %Z")
    let header_lines = [
        "# Generated by Yazelix"
        $"# Timestamp: ($generated_at)"
        $"# Source: ($generated_root)"
        $"# Config: ($default_config)"
        ""
    ]
    let header = ($header_lines | str join "\n")

    let mappings = [
        {terminal: "ghostty", source: "ghostty/config", dest: "ghostty/config"}
        {terminal: "wezterm", source: "wezterm/.wezterm.lua", dest: "wezterm/.wezterm.lua"}
        {terminal: "kitty", source: "kitty/kitty.conf", dest: "kitty/kitty.conf"}
        {terminal: "alacritty", source: "alacritty/alacritty.toml", dest: "alacritty/alacritty.toml"}
        {terminal: "foot", source: "foot/foot.ini", dest: "foot/foot.ini"}
    ]

    for entry in $mappings {
        let source_path = ($generated_root | path join $entry.source)
        if not ($source_path | path exists) {
            print $"⚠️  Skipping ($entry.terminal): no generated config at ($source_path)"
            continue
        }

        let dest_path = ($config_root | path join $entry.dest)
        let content = (open --raw $source_path)
        let final_content = $"($header)($content)"
        $final_content | save $dest_path --force
        print $"✅ Synced ($entry.terminal) → ($dest_path)"
    }
}

export def "yzx dev sync_issues" [
    --dry-run  # Show the local GitHub→Beads reconciliation plan without mutating Beads
] {
    run_dev_issue_sync $dry_run
}

export def "yzx dev build_pane_orchestrator" [
    --sync  # Sync the built wasm into the repo/runtime paths after a successful build
] {
    build_pane_orchestrator_wasm $sync
}

export def "yzx dev build_popup_plugin" [
    --sync  # Sync the built wasm into the repo/runtime paths after a successful build
] {
    build_popup_plugin_wasm $sync
}

def clear_startup_profile_caches [] {
    let state_root = (get_yazelix_state_dir | path join "state")
    let cache_paths = [
        ($state_root | path join "rebuild_hash")
    ]
    for cache_path in $cache_paths {
        if ($cache_path | path exists) {
            rm -f $cache_path
        }
    }
}

def build_profile_metadata [scenario: string, clear_cache: bool, repo_root: string] {
    {
        scenario: $scenario
        clear_cache: $clear_cache
        repo_root: $repo_root
        cwd: (pwd)
        in_yazelix_shell: (($env.IN_YAZELIX_SHELL? | default "") == "true")
        host: (sys host)
    }
}

def print_startup_profile_summary [summary: record] {
    print ""
    print "📊 Startup Profile Report"
    print $"   scenario: ($summary.run.scenario)"
    print $"   report: ($summary.report_path)"
    print $"   total: ($summary.total_duration_ms)ms"
    print ""
    print (render_startup_profile_summary $summary)
}

def run_dev_profile_harness [
    scenario: string
    startup_args: list<string>
    --clear-cache
] {
    let clear_cache_enabled = $clear_cache
    let repo_root = (require_yazelix_repo_root)
    let nu_bin = (resolve_yazelix_nu_bin)
    let start_script = ($repo_root | path join "nushell" "scripts" "core" "start_yazelix.nu")
    let profile_run = (create_startup_profile_run $scenario (build_profile_metadata $scenario $clear_cache_enabled $repo_root))

    if $clear_cache_enabled {
        clear_startup_profile_caches
    }

    let profile_env = (
        $profile_run.env
        | upsert YAZELIX_STARTUP_PROFILE_SKIP_WELCOME "true"
        | upsert YAZELIX_STARTUP_PROFILE_EXIT_BEFORE_ZELLIJ "true"
        | upsert YAZELIX_SHELLHOOK_SKIP_WELCOME "true"
    )
    let result = (with-env $profile_env {
        do { ^$nu_bin $start_script ...$startup_args } | complete
    })

    if $result.exit_code != 0 {
        error make {
            msg: "Startup profiling failed"
            label: {
                text: ($result.stderr | default $result.stdout | default "profiled startup exited unsuccessfully")
                span: (metadata $start_script).span
            }
        }
    }

    let summary = (load_startup_profile_report $profile_run.report_path)
    print_startup_profile_summary $summary
    $summary
}

def run_cold_profile_command [clear_cache: bool] {
    if (($env.IN_YAZELIX_SHELL? | default "") == "true") {
        print "❌ Error: Cold launch profiling must be run from a vanilla terminal"
        print ""
        print "To profile a cold startup path:"
        print "  1. Open a new terminal outside Yazelix"
        print "  2. Run: yzx dev profile --cold"
        return
    }

    print "🚀 Profiling cold Yazelix startup..."
    run_dev_profile_harness "enter_cold" [] --clear-cache=$clear_cache | ignore
}

def run_default_profile_command [] {
    let in_yazelix_shell = (($env.IN_YAZELIX_SHELL? | default "") == "true")
    if $in_yazelix_shell {
        print "🚀 Profiling warm Yazelix startup from the current shell..."
        run_dev_profile_harness "enter_warm" [] | ignore
    } else {
        print "⚠️  Not currently inside a Yazelix shell."
        print "   Profiling the default current-terminal startup path instead."
        print ""
        run_dev_profile_harness "enter_default" [] | ignore
    }
}

# Run Yazelix test suite
export def "yzx dev test" [
    --verbose(-v)  # Show detailed test output
    --new-window(-n)  # Run tests in a new Yazelix window
    --lint-only  # Run only syntax validation
    --profile  # Print timing summaries for the default suite
    --sweep  # Run the non-visual configuration sweep only
    --visual  # Run the visual terminal sweep only
    --all(-a)  # Run the default suite plus sweep + visual lanes
    --delay: int = 3  # Delay between visual terminal launches in seconds
] {
    use ../utils/test_runner.nu run_all_tests
    run_all_tests --verbose=$verbose --new-window=$new_window --lint-only=$lint_only --profile=$profile --sweep=$sweep --visual=$visual --all=$all --delay $delay
}

# Benchmark terminal launch performance
export def "yzx dev bench" [
    --iterations(-n): int = 1  # Number of iterations per terminal
    --terminal(-t): string     # Test only specific terminal
    --verbose(-v)              # Show detailed output
] {
    mut args = ["--iterations", $iterations]
    let requested_terminal = ($terminal | default "")

    if ($requested_terminal | is-not-empty) {
        $args = ($args | append ["--terminal", $requested_terminal])
    }

    if $verbose {
        $args = ($args | append "--verbose")
    }

    nu ((require_yazelix_repo_root) | path join "nushell" "scripts" "dev" "benchmark_terminals.nu") ...$args
}

# Profile launch sequence and identify bottlenecks
export def "yzx dev profile" [
    --cold(-c)        # Profile cold launch from vanilla terminal (emulates desktop entry or fresh terminal launch)
    --clear-cache     # Clear recorded runtime/project cache state first so the profiled run exercises the rebuild-heavy path
] {
    if $cold {
        run_cold_profile_command $clear_cache
    } else {
        run_default_profile_command
    }
}

# Lint Nushell scripts with repo-tuned nu-lint config from the maintainer tool surface
export def "yzx dev lint_nu" [
    --format(-f): string = "pretty"  # Output format: pretty or compact
    ...paths: string                 # Specific files or directories (default: nushell/)
] {
    let yazelix_dir = require_yazelix_repo_root
    let config_path = ($yazelix_dir | path join ".nu-lint.toml")

    if not ($config_path | path exists) {
        print $"Error: .nu-lint.toml not found at ($config_path)"
        exit 1
    }

    let targets = if ($paths | is-empty) {
        [($yazelix_dir | path join "nushell")]
    } else {
        $paths
    }
    if (which nu-lint | is-empty) {
        print "Error: nu-lint not found in PATH."
        print "Install nu-lint in your maintainer environment, then rerun this command."
        exit 1
    }

    ^nu-lint --config $config_path --format $format ...$targets
}
