# Generated by Yazelix
# Timestamp: 2026-04-12 11:41:39 -03:00
# Source: /home/lucca/.local/share/yazelix/configs/terminal_emulators
# Config: /home/lucca/pjs/yazelix/yazelix_default.toml
-- WezTerm configuration for Yazelix
local wezterm = require 'wezterm'
local config = wezterm.config_builder()

config.window_decorations = "NONE"
config.window_padding = { left = 0, right = 0, top = 10, bottom = 0 }
config.color_scheme = 'Abernathy'

-- Hide tab bar (Zellij handles tabs)
config.enable_tab_bar = false

-- Transparency (configurable via yazelix.toml)
config.window_background_opacity = 0.85

-- Cursor trails: Not supported in WezTerm

return config