use crate::bridge::{CoreError, ErrorClass};
use serde::Serialize;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;
use std::time::SystemTime;

const YAZELIX_WINDOW_CLASS: &str = "com.yazelix.Yazelix";
const YAZELIX_X11_INSTANCE: &str = "yazelix";
const YAZELIX_THEME: &str = "Abernathy";
// Font constant available for future terminal materialization
// const FONT_FIRACODE: &str = "FiraCode Nerd Font";

const GHOSTTY_CONFIG_HEADER: &str =
    "# Yazelix-managed Ghostty configuration\n# Generated by Yazelix — do not edit directly.";

const TRANSPARENCY_VALUES: &[(&str, &str)] = &[
    ("none", "1.0"),
    ("very_low", "0.95"),
    ("low", "0.90"),
    ("medium", "0.85"),
    ("high", "0.80"),
    ("very_high", "0.70"),
    ("super_high", "0.60"),
];

const CURSOR_TRAIL_SHADERS: &[(&str, &str)] = &[
    ("blaze", "./shaders/cursor_trail_blaze.glsl"),
    ("snow", "./shaders/cursor_trail_white.glsl"),
    ("cosmic", "./shaders/cursor_trail_cosmic.glsl"),
    ("ocean", "./shaders/cursor_trail_ocean.glsl"),
    ("forest", "./shaders/cursor_trail_forest.glsl"),
    ("sunset", "./shaders/cursor_trail_sunset.glsl"),
    ("neon", "./shaders/cursor_trail_neon.glsl"),
    ("party", "./shaders/cursor_trail_party.glsl"),
    ("eclipse", "./shaders/cursor_trail_eclipse.glsl"),
    ("dusk", "./shaders/cursor_trail_dusk.glsl"),
    ("orchid", "./shaders/cursor_trail_orchid.glsl"),
    ("reef", "./shaders/cursor_trail_reef.glsl"),
    ("inferno", "./shaders/cursor_trail_inferno.glsl"),
    ("none", ""),
];

const CURSOR_TRAIL_COLOR_HEX: &[(&str, &str)] = &[
    ("blaze", "#ffb929"),
    ("snow", "#ffffff"),
    ("cosmic", "#c761f5"),
    ("ocean", "#5ea8ff"),
    ("forest", "#3bd17a"),
    ("sunset", "#ff7a59"),
    ("neon", "#0090ff"),
    ("party", "#ff00ff"),
    ("eclipse", "#ffd400"),
    ("dusk", "#e94560"),
    ("orchid", "#ff6b00"),
    ("reef", "#00e6ff"),
    ("inferno", "#ff1600"),
];

const CURSOR_TRAIL_COLOR_LITERALS: &[(&str, &str)] = &[
    ("blaze", "vec4(1.0, 0.725, 0.161, 1.0)"),
    ("snow", "vec4(1.0, 1.0, 1.0, 1.0)"),
    ("cosmic", "vec4(0.78, 0.38, 0.96, 1.0)"),
    ("ocean", "vec4(0.37, 0.66, 1.00, 1.0)"),
    ("forest", "vec4(0.23, 0.82, 0.48, 1.0)"),
    ("sunset", "vec4(1.00, 0.48, 0.35, 1.0)"),
    ("neon", "vec4(0.00, 0.565, 1.00, 1.0)"),
    ("party", "vec4(1.00, 0.00, 1.00, 1.0)"),
    ("eclipse", "vec4(1.000, 0.831, 0.000, 1.0)"),
    ("dusk", "vec4(0.914, 0.271, 0.376, 1.0)"),
    ("orchid", "vec4(1.0, 0.420, 0.0, 1.0)"),
    ("reef", "vec4(0.0, 0.902, 1.0, 1.0)"),
    ("inferno", "vec4(1.0, 0.086, 0.0, 1.0)"),
];

const GHOSTTY_TRAIL_EFFECTS: &[&str] = &["tail", "warp", "sweep"];
const GHOSTTY_MODE_EFFECTS: &[&str] =
    &["ripple", "sonic_boom", "rectangle_boom", "ripple_rectangle"];
pub const DEFAULT_GHOSTTY_TRAIL_DURATION: f64 = 1.0;
pub const GHOSTTY_TRAIL_DURATION_MIN: f64 = 0.25;
pub const GHOSTTY_TRAIL_DURATION_MAX: f64 = 4.0;

const EFFECTS_REQUIRING_ALWAYS_ANIMATION: &[&str] =
    &["ripple", "sonic_boom", "rectangle_boom", "ripple_rectangle"];

#[derive(Debug, Clone)]
pub struct GhosttyMaterializationRequest {
    pub runtime_dir: PathBuf,
    pub config_dir: PathBuf,
    pub state_dir: PathBuf,
    pub transparency: String,
    pub ghostty_trail_color: Option<String>,
    pub ghostty_trail_effect: Option<String>,
    pub ghostty_mode_effect: Option<String>,
    pub ghostty_trail_duration: f64,
    pub ghostty_trail_glow: String,
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct GhosttyCursorState {
    pub selected_color: Option<String>,
    pub selected_trail_effect: Option<String>,
    pub selected_mode_effect: Option<String>,
    pub trail_duration: f64,
    pub effect_color_literal: String,
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct GhosttyMaterializationData {
    pub generated_path: String,
    pub cursor_state: GhosttyCursorState,
    pub shaders_synced: bool,
}

fn get_opacity_value(transparency: &str) -> &str {
    TRANSPARENCY_VALUES
        .iter()
        .find(|(k, _)| *k == transparency)
        .map(|(_, v)| *v)
        .unwrap_or("1.0")
}

fn pick_random<'a>(pool: &[&'a str]) -> Option<&'a str> {
    if pool.is_empty() {
        return None;
    }
    let len = pool.len();
    let index = SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| (d.as_nanos() as usize) % len)
        .unwrap_or(0);
    pool.get(index).copied()
}

fn resolve_ghostty_trail_color(color: &Option<String>) -> Option<String> {
    match color.as_deref() {
        None | Some("") => None,
        Some("random") => {
            let pool: Vec<&str> = CURSOR_TRAIL_SHADERS
                .iter()
                .filter(|(k, _)| *k != "none" && *k != "party")
                .map(|(k, _)| *k)
                .collect();
            pick_random(&pool).map(String::from)
        }
        Some(other) => Some(other.to_string()),
    }
}

fn resolve_ghostty_trail_effect(effect: &Option<String>) -> Option<String> {
    match effect.as_deref() {
        None | Some("") => None,
        Some("random") => pick_random(GHOSTTY_TRAIL_EFFECTS).map(String::from),
        Some(other) => Some(other.to_string()),
    }
}

fn resolve_ghostty_mode_effect(effect: &Option<String>) -> Option<String> {
    match effect.as_deref() {
        None | Some("") => None,
        Some("random") => pick_random(GHOSTTY_MODE_EFFECTS).map(String::from),
        Some(other) => Some(other.to_string()),
    }
}

fn get_ghostty_cursor_color_hex(selected_color: &str) -> &str {
    CURSOR_TRAIL_COLOR_HEX
        .iter()
        .find(|(k, _)| *k == selected_color)
        .map(|(_, v)| *v)
        .unwrap_or("#ffb929")
}

fn get_ghostty_cursor_effect_color_literal(selected_color: &Option<String>) -> String {
    match selected_color.as_deref() {
        None | Some("none") => "iCurrentCursorColor".to_string(),
        Some(color) => CURSOR_TRAIL_COLOR_LITERALS
            .iter()
            .find(|(k, _)| *k == color)
            .map(|(_, v)| v.to_string())
            .unwrap_or_else(|| "iCurrentCursorColor".to_string()),
    }
}

fn get_cursor_trail_shader(selected_color: &str) -> &str {
    CURSOR_TRAIL_SHADERS
        .iter()
        .find(|(k, _)| *k == selected_color)
        .map(|(_, v)| *v)
        .unwrap_or("")
}

fn ghostty_effect_requires_always_animation(effect: &str) -> bool {
    EFFECTS_REQUIRING_ALWAYS_ANIMATION.contains(&effect)
}

fn get_terminal_override_path(config_dir: &Path, terminal: &str) -> Option<PathBuf> {
    let override_dir = config_dir.join("user_configs").join("terminal");
    match terminal {
        "ghostty" => Some(override_dir.join("ghostty")),
        "kitty" => Some(override_dir.join("kitty.conf")),
        "alacritty" => Some(override_dir.join("alacritty.toml")),
        _ => None,
    }
}

fn build_ghostty_transparency(transparency: &str) -> String {
    let opacity = get_opacity_value(transparency);
    let opacity_line = if transparency == "none" {
        format!("# background-opacity = {}", opacity)
    } else {
        format!("background-opacity = {}", opacity)
    };

    if transparency == "none" {
        opacity_line
    } else {
        format!("{}\nbackground-opacity-cells = true", opacity_line)
    }
}

fn validate_ghostty_trail_duration(duration: f64) -> Result<(), CoreError> {
    if !duration.is_finite()
        || !(GHOSTTY_TRAIL_DURATION_MIN..=GHOSTTY_TRAIL_DURATION_MAX).contains(&duration)
    {
        return Err(CoreError::classified(
            ErrorClass::Config,
            "invalid_ghostty_trail_duration",
            format!(
                "Invalid terminal.ghostty_trail_duration value '{}'. Expected a number from {} to {}.",
                duration, GHOSTTY_TRAIL_DURATION_MIN, GHOSTTY_TRAIL_DURATION_MAX
            ),
            "Update yazelix.toml with a supported Ghostty trail duration multiplier, then retry.",
            serde_json::json!({
                "field": "terminal.ghostty_trail_duration",
                "actual": duration.to_string(),
                "min": GHOSTTY_TRAIL_DURATION_MIN,
                "max": GHOSTTY_TRAIL_DURATION_MAX,
            }),
        ));
    }
    Ok(())
}

fn format_ghostty_trail_duration(duration: f64) -> String {
    let mut rendered = format!("{duration:.3}");
    while rendered.contains('.') && rendered.ends_with('0') {
        rendered.pop();
    }
    if rendered.ends_with('.') {
        rendered.push('0');
    }
    rendered
}

fn build_ghostty_trail_duration(duration: f64) -> String {
    format!(
        "# Ghostty trail duration multiplier: {}",
        format_ghostty_trail_duration(duration)
    )
}

fn build_ghostty_cursor_palette(selected_color: &Option<String>) -> String {
    match selected_color.as_deref() {
        None => "# cursor-color = #ffb929".to_string(),
        Some("none") => {
            "# Cursor color palette: none (disable Yazelix color trail palette)".to_string()
        }
        Some(color) => {
            let hex = get_ghostty_cursor_color_hex(color);
            let shader = get_cursor_trail_shader(color);
            format!(
                "# Cursor color palette: {}\ncursor-color = {}\ncustom-shader = {}",
                color, hex, shader
            )
        }
    }
}

fn build_ghostty_cursor_effects(
    trail_effect: &Option<String>,
    mode_effect: &Option<String>,
) -> String {
    let selected_effects: Vec<&str> = [trail_effect.as_deref(), mode_effect.as_deref()]
        .into_iter()
        .flatten()
        .filter(|e| !e.is_empty())
        .collect();

    if selected_effects.is_empty() {
        return "# custom-shader = ./shaders/generated_effects/tail.glsl".to_string();
    }

    let mut lines = vec![format!("# Cursor effects: {}", selected_effects.join(", "))];

    if let Some(mode) = mode_effect {
        if ghostty_effect_requires_always_animation(mode) {
            lines.push("custom-shader-animation = always".to_string());
        }
    }

    for effect in selected_effects {
        lines.push(format!(
            "custom-shader = ./shaders/generated_effects/{}.glsl",
            effect
        ));
    }

    lines.join("\n")
}

fn resolve_ghostty_cursor_render_state(
    request: &GhosttyMaterializationRequest,
) -> GhosttyCursorState {
    let selected_color = resolve_ghostty_trail_color(&request.ghostty_trail_color);
    GhosttyCursorState {
        selected_color: selected_color.clone(),
        selected_trail_effect: resolve_ghostty_trail_effect(&request.ghostty_trail_effect),
        selected_mode_effect: resolve_ghostty_mode_effect(&request.ghostty_mode_effect),
        trail_duration: request.ghostty_trail_duration,
        effect_color_literal: get_ghostty_cursor_effect_color_literal(&selected_color),
    }
}

fn build_ghostty_config(
    request: &GhosttyMaterializationRequest,
    cursor_state: &GhosttyCursorState,
) -> String {
    let override_path = get_terminal_override_path(&request.config_dir, "ghostty")
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_default();

    format!(
        r#"{}

# Yazelix branding for desktop environment recognition
class = {}
x11-instance-name = {}
title = Yazelix - Ghostty

# Theme and styling
theme = "{}"
window-decoration = "none"
window-padding-y = 10,0

# Transparency (configurable via yazelix.toml)
{}

# Ghostty cursor color + effects (configurable via yazelix.toml)
{}
{}
{}

# Personal Yazelix Ghostty overrides (optional, user-owned)
config-file = ?"{}"
"#,
        GHOSTTY_CONFIG_HEADER,
        YAZELIX_WINDOW_CLASS,
        YAZELIX_X11_INSTANCE,
        YAZELIX_THEME,
        build_ghostty_transparency(&request.transparency),
        build_ghostty_cursor_palette(&cursor_state.selected_color),
        build_ghostty_trail_duration(request.ghostty_trail_duration),
        build_ghostty_cursor_effects(
            &cursor_state.selected_trail_effect,
            &cursor_state.selected_mode_effect
        ),
        override_path,
    )
}

fn sync_ghostty_shader_assets(
    runtime_dir: &Path,
    ghostty_dir: &Path,
    glow_level: &str,
    effect_color_literal: &str,
    trail_duration: f64,
) -> Result<bool, CoreError> {
    let shaders_src = runtime_dir
        .join("configs")
        .join("terminal_emulators")
        .join("ghostty")
        .join("shaders");
    let shaders_dest = ghostty_dir.join("shaders");

    if shaders_dest.exists() {
        // Make writable before removing
        let _ = Command::new("chmod")
            .args(["-R", "u+w", &shaders_dest.to_string_lossy()])
            .output();

        fs::remove_dir_all(&shaders_dest).map_err(|source| {
            CoreError::io(
                "remove_ghostty_shaders",
                "Failed to remove previous Ghostty shader assets",
                "Check permissions for the Yazelix state directory and retry.",
                shaders_dest.to_string_lossy(),
                source,
            )
        })?;
    }

    fs::create_dir_all(&shaders_dest).map_err(|source| {
        CoreError::io(
            "create_ghostty_shaders",
            "Could not create the Ghostty shader output directory",
            "Check permissions for the Yazelix state directory and retry.",
            shaders_dest.to_string_lossy(),
            source,
        )
    })?;

    if shaders_src.exists() {
        // Copy shaders directory recursively
        copy_dir_all(&shaders_src, &shaders_dest).map_err(|source| {
            CoreError::io(
                "copy_ghostty_shaders",
                "Failed to copy Ghostty shader assets",
                "Check permissions and disk space, then retry.",
                format!("{} -> {}", shaders_src.display(), shaders_dest.display()),
                source,
            )
        })?;

        // Make writable
        let _ = Command::new("chmod")
            .args(["-R", "u+w", &shaders_dest.to_string_lossy()])
            .output();
    }

    // Run the shader build script if it exists
    let build_script = shaders_src.join("build_shaders.nu");
    if build_script.exists() {
        let build_script_name = build_script
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| "build_shaders.nu".to_string());
        let output = Command::new("nu")
            .arg(&build_script_name)
            .arg(glow_level)
            .arg(&shaders_dest)
            .arg(effect_color_literal)
            .arg(format_ghostty_trail_duration(trail_duration))
            .current_dir(&shaders_src)
            .output()
            .map_err(|source| {
                CoreError::io(
                    "run_ghostty_shader_build",
                    "Failed to run Ghostty shader build script",
                    "Ensure Nushell is installed and accessible on PATH.",
                    build_script.to_string_lossy(),
                    source,
                )
            })?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(CoreError::classified(
                ErrorClass::Runtime,
                "ghostty_shader_build_failed",
                format!("Ghostty shader build script failed: {}", stderr.trim()),
                "Check the shader build script for errors and retry.",
                serde_json::json!({"script": build_script.to_string_lossy()}),
            ));
        }
    }

    Ok(true)
}

fn copy_dir_all(src: impl AsRef<Path>, dst: impl AsRef<Path>) -> std::io::Result<()> {
    fs::create_dir_all(&dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        let src_path = entry.path();
        let dst_path = dst.as_ref().join(entry.file_name());
        if ty.is_dir() {
            copy_dir_all(&src_path, &dst_path)?;
        } else {
            fs::copy(&src_path, &dst_path)?;
        }
    }
    Ok(())
}

pub fn generate_ghostty_materialization(
    request: &GhosttyMaterializationRequest,
) -> Result<GhosttyMaterializationData, CoreError> {
    validate_ghostty_trail_duration(request.ghostty_trail_duration)?;
    let cursor_state = resolve_ghostty_cursor_render_state(request);

    let ghostty_dir = request
        .state_dir
        .join("configs")
        .join("terminal_emulators")
        .join("ghostty");

    fs::create_dir_all(&ghostty_dir).map_err(|source| {
        CoreError::io(
            "create_ghostty_output_dir",
            "Could not create the managed Ghostty output directory",
            "Check permissions for the Yazelix state directory and retry.",
            ghostty_dir.to_string_lossy(),
            source,
        )
    })?;

    let config_content = build_ghostty_config(request, &cursor_state);
    let generated_path = ghostty_dir.join("config");

    fs::write(&generated_path, config_content).map_err(|source| {
        CoreError::io(
            "write_ghostty_config",
            "Could not write the managed Ghostty config",
            "Check permissions for the Yazelix state directory and retry.",
            generated_path.to_string_lossy(),
            source,
        )
    })?;

    let shaders_synced = sync_ghostty_shader_assets(
        &request.runtime_dir,
        &ghostty_dir,
        &request.ghostty_trail_glow,
        &cursor_state.effect_color_literal,
        request.ghostty_trail_duration,
    )?;

    Ok(GhosttyMaterializationData {
        generated_path: generated_path.to_string_lossy().into_owned(),
        cursor_state,
        shaders_synced,
    })
}
