use crate::appearance_mode::ghostty_theme;
use crate::atomic_fs::write_text_atomic;
use crate::bridge::CoreError;
use crate::ghostty_cursor_registry::format_ghostty_trail_duration;
pub use crate::ghostty_cursor_registry::{
    DEFAULT_GHOSTTY_TRAIL_DURATION, GHOSTTY_TRAIL_DURATION_MAX, GHOSTTY_TRAIL_DURATION_MIN,
};
use crate::runtime_component_enabled;
use crate::terminal_cursor_materialization::{
    TerminalCursorMaterializationRequest, TerminalCursorState, disabled_terminal_cursor_state,
    generate_terminal_cursor_materialization,
};
use crate::user_config_paths;
use serde::Serialize;
use std::fs;
use std::path::{Path, PathBuf};

const YAZELIX_WINDOW_CLASS: &str = "com.yazelix.Yazelix";
const YAZELIX_X11_INSTANCE: &str = "yazelix";
// Font constant available for future terminal materialization
// const FONT_FIRACODE: &str = "FiraCode Nerd Font";

const GHOSTTY_CONFIG_HEADER: &str =
    "# Yazelix-managed Ghostty configuration\n# Generated by Yazelix — do not edit directly.";

const TRANSPARENCY_VALUES: &[(&str, &str)] = &[
    ("none", "1.0"),
    ("very_low", "0.95"),
    ("low", "0.90"),
    ("medium", "0.85"),
    ("high", "0.80"),
    ("very_high", "0.70"),
    ("super_high", "0.60"),
];

const EFFECTS_REQUIRING_ALWAYS_ANIMATION: &[&str] =
    &["ripple", "sonic_boom", "rectangle_boom", "ripple_rectangle"];

#[derive(Debug, Clone)]
pub struct GhosttyMaterializationRequest {
    pub runtime_dir: PathBuf,
    pub config_dir: PathBuf,
    pub state_dir: PathBuf,
    pub transparency: String,
    pub appearance_mode: String,
    pub cursor_config_path: PathBuf,
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct GhosttyMaterializationData {
    pub generated_path: String,
    pub cursor_state: TerminalCursorState,
    pub shaders_synced: bool,
}

fn get_opacity_value(transparency: &str) -> &str {
    TRANSPARENCY_VALUES
        .iter()
        .find(|(k, _)| *k == transparency)
        .map(|(_, v)| *v)
        .unwrap_or("1.0")
}

fn ghostty_effect_requires_always_animation(effect: &str) -> bool {
    EFFECTS_REQUIRING_ALWAYS_ANIMATION.contains(&effect)
}

fn get_terminal_override_path(
    config_dir: &Path,
    terminal: &str,
) -> Result<Option<PathBuf>, CoreError> {
    let Some(current) = user_config_paths::terminal_config(config_dir, terminal) else {
        return Ok(None);
    };
    let Some(legacy) = user_config_paths::legacy_terminal_config(config_dir, terminal) else {
        return Ok(None);
    };
    let path = user_config_paths::resolve_current_config_file(
        &current,
        &legacy,
        &format!("{terminal} terminal override"),
    )?;
    Ok(Some(path))
}

fn build_ghostty_transparency(transparency: &str) -> String {
    let opacity = get_opacity_value(transparency);
    let opacity_line = if transparency == "none" {
        format!("# background-opacity = {}", opacity)
    } else {
        format!("background-opacity = {}", opacity)
    };

    if transparency == "none" {
        opacity_line
    } else {
        format!("{}\nbackground-opacity-cells = true", opacity_line)
    }
}

fn build_ghostty_trail_duration(duration: f64) -> String {
    format!(
        "# Ghostty trail duration multiplier: {}",
        format_ghostty_trail_duration(duration)
    )
}

fn ghostty_shader_path(ghostty_dir: &Path, relative_path: impl AsRef<Path>) -> String {
    ghostty_dir
        .join("shaders")
        .join(relative_path)
        .to_string_lossy()
        .into_owned()
}

fn build_ghostty_cursor_palette(ghostty_dir: &Path, cursor_state: &TerminalCursorState) -> String {
    if cursor_state.selected_color.as_deref() == Some("none") {
        return "# Cursor color palette: none (disabled in settings.jsonc)".to_string();
    }

    let Some(name) = cursor_state.selected_color.as_deref() else {
        return "# cursor-color = #ffb929".to_string();
    };
    let Some(color_hex) = cursor_state.selected_color_hex.as_deref() else {
        return "# cursor-color = #ffb929".to_string();
    };

    let shader_path = ghostty_shader_path(ghostty_dir, format!("cursor_trail_{}.glsl", name));
    format!(
        "# Cursor color palette: {}\ncursor-color = {}\ncustom-shader = {}",
        name, color_hex, shader_path
    )
}

fn build_ghostty_cursor_effects(
    ghostty_dir: &Path,
    trail_effect: &Option<String>,
    mode_effect: &Option<String>,
) -> String {
    let selected_effects: Vec<&str> = [trail_effect.as_deref(), mode_effect.as_deref()]
        .into_iter()
        .flatten()
        .filter(|e| !e.is_empty())
        .collect();

    if selected_effects.is_empty() {
        return format!(
            "# custom-shader = {}",
            ghostty_shader_path(ghostty_dir, "generated_effects/tail.glsl")
        );
    }

    let mut lines = vec![format!("# Cursor effects: {}", selected_effects.join(", "))];

    if let Some(mode) = mode_effect {
        if ghostty_effect_requires_always_animation(mode) {
            lines.push("custom-shader-animation = always".to_string());
        }
    }

    for effect in selected_effects {
        lines.push(format!(
            "custom-shader = {}",
            ghostty_shader_path(ghostty_dir, format!("generated_effects/{effect}.glsl"))
        ));
    }

    lines.join("\n")
}

fn build_ghostty_config_without_cursor(
    request: &GhosttyMaterializationRequest,
) -> Result<String, CoreError> {
    let override_path = get_terminal_override_path(&request.config_dir, "ghostty")?
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_default();

    Ok(format!(
        r#"{}

# Yazelix desktop identity
class = {}
x11-instance-name = {}

# Theme and styling
theme = "{}"
window-decoration = "none"
window-padding-y = 10,0

# Transparency (configurable via settings.jsonc)
{}

# Ghostty cursor color + effects
# Yazelix cursor component disabled by this runtime

# Personal Yazelix Ghostty overrides (optional, user-owned)
config-file = ?"{}"
"#,
        GHOSTTY_CONFIG_HEADER,
        YAZELIX_WINDOW_CLASS,
        YAZELIX_X11_INSTANCE,
        ghostty_theme(&request.appearance_mode),
        build_ghostty_transparency(&request.transparency),
        override_path,
    ))
}

fn build_ghostty_config(
    request: &GhosttyMaterializationRequest,
    ghostty_dir: &Path,
    cursor_state: &TerminalCursorState,
) -> Result<String, CoreError> {
    let override_path = get_terminal_override_path(&request.config_dir, "ghostty")?
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_default();

    Ok(format!(
        r#"{}

# Yazelix desktop identity
class = {}
x11-instance-name = {}

# Theme and styling
theme = "{}"
window-decoration = "none"
window-padding-y = 10,0

# Transparency (configurable via settings.jsonc)
{}

# Ghostty cursor color + effects (configurable via settings.jsonc)
{}
{}
{}

# Personal Yazelix Ghostty overrides (optional, user-owned)
config-file = ?"{}"
"#,
        GHOSTTY_CONFIG_HEADER,
        YAZELIX_WINDOW_CLASS,
        YAZELIX_X11_INSTANCE,
        ghostty_theme(&request.appearance_mode),
        build_ghostty_transparency(&request.transparency),
        build_ghostty_cursor_palette(ghostty_dir, cursor_state),
        build_ghostty_trail_duration(cursor_state.trail_duration),
        build_ghostty_cursor_effects(
            ghostty_dir,
            &cursor_state.selected_trail_effect,
            &cursor_state.selected_mode_effect
        ),
        override_path,
    ))
}

pub fn generate_ghostty_materialization(
    request: &GhosttyMaterializationRequest,
) -> Result<GhosttyMaterializationData, CoreError> {
    let ghostty_dir = request
        .state_dir
        .join("configs")
        .join("terminal_emulators")
        .join("ghostty");

    fs::create_dir_all(&ghostty_dir).map_err(|source| {
        CoreError::io(
            "create_ghostty_output_dir",
            "Could not create the managed Ghostty output directory",
            "Check permissions for the Yazelix state directory and retry.",
            ghostty_dir.to_string_lossy(),
            source,
        )
    })?;

    if !runtime_component_enabled(&request.runtime_dir, "cursors")? {
        let generated_path = ghostty_dir.join("config");
        write_text_atomic(
            &generated_path,
            &build_ghostty_config_without_cursor(request)?,
        )?;
        return Ok(GhosttyMaterializationData {
            generated_path: generated_path.to_string_lossy().into_owned(),
            cursor_state: disabled_terminal_cursor_state(),
            shaders_synced: false,
        });
    }

    let cursor_data =
        generate_terminal_cursor_materialization(&TerminalCursorMaterializationRequest {
            runtime_dir: request.runtime_dir.clone(),
            state_dir: request.state_dir.clone(),
            cursor_config_path: request.cursor_config_path.clone(),
            appearance_mode: request.appearance_mode.clone(),
        })?;
    let cursor_state = cursor_data.cursor_state;
    let config_content = build_ghostty_config(request, &ghostty_dir, &cursor_state)?;
    let generated_path = ghostty_dir.join("config");

    write_text_atomic(&generated_path, &config_content)?;

    Ok(GhosttyMaterializationData {
        generated_path: generated_path.to_string_lossy().into_owned(),
        cursor_state,
        shaders_synced: cursor_data.shaders_synced,
    })
}
