use crate::bridge::{CoreError, ErrorClass};
use crate::ghostty_cursor_registry::{
    CursorDefinition, CursorFamily, CursorRegistry, ResolvedCursorRegistryState,
};
pub use crate::ghostty_cursor_registry::{
    DEFAULT_GHOSTTY_TRAIL_DURATION, GHOSTTY_TRAIL_DURATION_MAX, GHOSTTY_TRAIL_DURATION_MIN,
};
use serde::Serialize;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

const YAZELIX_WINDOW_CLASS: &str = "com.yazelix.Yazelix";
const YAZELIX_X11_INSTANCE: &str = "yazelix";
const YAZELIX_THEME: &str = "Abernathy";
// Font constant available for future terminal materialization
// const FONT_FIRACODE: &str = "FiraCode Nerd Font";

const GHOSTTY_CONFIG_HEADER: &str =
    "# Yazelix-managed Ghostty configuration\n# Generated by Yazelix — do not edit directly.";

const TRANSPARENCY_VALUES: &[(&str, &str)] = &[
    ("none", "1.0"),
    ("very_low", "0.95"),
    ("low", "0.90"),
    ("medium", "0.85"),
    ("high", "0.80"),
    ("very_high", "0.70"),
    ("super_high", "0.60"),
];

const EFFECTS_REQUIRING_ALWAYS_ANIMATION: &[&str] =
    &["ripple", "sonic_boom", "rectangle_boom", "ripple_rectangle"];

#[derive(Debug, Clone)]
pub struct GhosttyMaterializationRequest {
    pub runtime_dir: PathBuf,
    pub config_dir: PathBuf,
    pub state_dir: PathBuf,
    pub transparency: String,
    pub cursor_config_path: PathBuf,
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct GhosttyCursorState {
    pub selected_color: Option<String>,
    pub selected_trail_effect: Option<String>,
    pub selected_mode_effect: Option<String>,
    pub trail_duration: f64,
    pub effect_color_literal: String,
}

#[derive(Debug, Clone, Serialize, PartialEq)]
pub struct GhosttyMaterializationData {
    pub generated_path: String,
    pub cursor_state: GhosttyCursorState,
    pub shaders_synced: bool,
}

fn get_opacity_value(transparency: &str) -> &str {
    TRANSPARENCY_VALUES
        .iter()
        .find(|(k, _)| *k == transparency)
        .map(|(_, v)| *v)
        .unwrap_or("1.0")
}

fn ghostty_effect_requires_always_animation(effect: &str) -> bool {
    EFFECTS_REQUIRING_ALWAYS_ANIMATION.contains(&effect)
}

fn get_terminal_override_path(config_dir: &Path, terminal: &str) -> Option<PathBuf> {
    let override_dir = config_dir.join("user_configs").join("terminal");
    match terminal {
        "ghostty" => Some(override_dir.join("ghostty")),
        "kitty" => Some(override_dir.join("kitty.conf")),
        "alacritty" => Some(override_dir.join("alacritty.toml")),
        _ => None,
    }
}

fn build_ghostty_transparency(transparency: &str) -> String {
    let opacity = get_opacity_value(transparency);
    let opacity_line = if transparency == "none" {
        format!("# background-opacity = {}", opacity)
    } else {
        format!("background-opacity = {}", opacity)
    };

    if transparency == "none" {
        opacity_line
    } else {
        format!("{}\nbackground-opacity-cells = true", opacity_line)
    }
}

fn validate_ghostty_trail_duration(duration: f64) -> Result<(), CoreError> {
    if !duration.is_finite()
        || !(GHOSTTY_TRAIL_DURATION_MIN..=GHOSTTY_TRAIL_DURATION_MAX).contains(&duration)
    {
        return Err(CoreError::classified(
            ErrorClass::Config,
            "invalid_ghostty_trail_duration",
            format!(
                "Invalid cursor settings.duration value '{}'. Expected a number from {} to {}.",
                duration, GHOSTTY_TRAIL_DURATION_MIN, GHOSTTY_TRAIL_DURATION_MAX
            ),
            "Update user_configs/yazelix_cursors.toml with a supported Ghostty trail duration multiplier, then retry.",
            serde_json::json!({
                "field": "settings.duration",
                "actual": duration.to_string(),
                "min": GHOSTTY_TRAIL_DURATION_MIN,
                "max": GHOSTTY_TRAIL_DURATION_MAX,
            }),
        ));
    }
    Ok(())
}

fn format_ghostty_trail_duration(duration: f64) -> String {
    let mut rendered = format!("{duration:.3}");
    while rendered.contains('.') && rendered.ends_with('0') {
        rendered.pop();
    }
    if rendered.ends_with('.') {
        rendered.push('0');
    }
    rendered
}

fn build_ghostty_trail_duration(duration: f64) -> String {
    format!(
        "# Ghostty trail duration multiplier: {}",
        format_ghostty_trail_duration(duration)
    )
}

fn build_ghostty_cursor_palette(cursor_state: &ResolvedCursorRegistryState) -> String {
    if cursor_state.trail_disabled {
        return "# Cursor color palette: none (disabled in yazelix_cursors.toml)".to_string();
    }

    let Some(cursor) = &cursor_state.selected_cursor else {
        return "# cursor-color = #ffb929".to_string();
    };

    format!(
        "# Cursor color palette: {}\ncursor-color = {}\ncustom-shader = {}",
        cursor.name,
        cursor.cursor_color_hex(),
        cursor.shader_path()
    )
}

fn build_ghostty_cursor_effects(
    trail_effect: &Option<String>,
    mode_effect: &Option<String>,
) -> String {
    let selected_effects: Vec<&str> = [trail_effect.as_deref(), mode_effect.as_deref()]
        .into_iter()
        .flatten()
        .filter(|e| !e.is_empty())
        .collect();

    if selected_effects.is_empty() {
        return "# custom-shader = ./shaders/generated_effects/tail.glsl".to_string();
    }

    let mut lines = vec![format!("# Cursor effects: {}", selected_effects.join(", "))];

    if let Some(mode) = mode_effect {
        if ghostty_effect_requires_always_animation(mode) {
            lines.push("custom-shader-animation = always".to_string());
        }
    }

    for effect in selected_effects {
        lines.push(format!(
            "custom-shader = ./shaders/generated_effects/{}.glsl",
            effect
        ));
    }

    lines.join("\n")
}

fn build_ghostty_cursor_render_state(
    registry_state: &ResolvedCursorRegistryState,
) -> GhosttyCursorState {
    let selected_color = if registry_state.trail_disabled {
        Some("none".to_string())
    } else {
        registry_state
            .selected_cursor
            .as_ref()
            .map(|cursor| cursor.name.clone())
    };
    GhosttyCursorState {
        selected_color,
        selected_trail_effect: registry_state.selected_trail_effect.clone(),
        selected_mode_effect: registry_state.selected_mode_effect.clone(),
        trail_duration: registry_state.duration,
        effect_color_literal: registry_state
            .selected_cursor
            .as_ref()
            .map(CursorDefinition::cursor_color_literal)
            .unwrap_or_else(|| "iCurrentCursorColor".to_string()),
    }
}

fn build_ghostty_config(
    request: &GhosttyMaterializationRequest,
    cursor_state: &GhosttyCursorState,
    registry_state: &ResolvedCursorRegistryState,
) -> String {
    let override_path = get_terminal_override_path(&request.config_dir, "ghostty")
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_default();

    format!(
        r#"{}

# Yazelix branding for desktop environment recognition
class = {}
x11-instance-name = {}
title = Yazelix - Ghostty

# Theme and styling
theme = "{}"
window-decoration = "none"
window-padding-y = 10,0

# Transparency (configurable via yazelix.toml)
{}

# Ghostty cursor color + effects (configurable via yazelix_cursors.toml)
{}
{}
{}

# Personal Yazelix Ghostty overrides (optional, user-owned)
config-file = ?"{}"
"#,
        GHOSTTY_CONFIG_HEADER,
        YAZELIX_WINDOW_CLASS,
        YAZELIX_X11_INSTANCE,
        YAZELIX_THEME,
        build_ghostty_transparency(&request.transparency),
        build_ghostty_cursor_palette(registry_state),
        build_ghostty_trail_duration(cursor_state.trail_duration),
        build_ghostty_cursor_effects(
            &cursor_state.selected_trail_effect,
            &cursor_state.selected_mode_effect
        ),
        override_path,
    )
}

fn sync_ghostty_shader_assets(
    runtime_dir: &Path,
    ghostty_dir: &Path,
    glow_level: &str,
    effect_color_literal: &str,
    trail_duration: f64,
    registry: &CursorRegistry,
) -> Result<bool, CoreError> {
    let shaders_src = runtime_dir
        .join("configs")
        .join("terminal_emulators")
        .join("ghostty")
        .join("shaders");
    let shaders_dest = ghostty_dir.join("shaders");

    if shaders_dest.exists() {
        // Make writable before removing
        let _ = Command::new("chmod")
            .args(["-R", "u+w", &shaders_dest.to_string_lossy()])
            .output();

        fs::remove_dir_all(&shaders_dest).map_err(|source| {
            CoreError::io(
                "remove_ghostty_shaders",
                "Failed to remove previous Ghostty shader assets",
                "Check permissions for the Yazelix state directory and retry.",
                shaders_dest.to_string_lossy(),
                source,
            )
        })?;
    }

    fs::create_dir_all(&shaders_dest).map_err(|source| {
        CoreError::io(
            "create_ghostty_shaders",
            "Could not create the Ghostty shader output directory",
            "Check permissions for the Yazelix state directory and retry.",
            shaders_dest.to_string_lossy(),
            source,
        )
    })?;

    if shaders_src.exists() {
        // Copy shaders directory recursively
        copy_dir_all(&shaders_src, &shaders_dest).map_err(|source| {
            CoreError::io(
                "copy_ghostty_shaders",
                "Failed to copy Ghostty shader assets",
                "Check permissions and disk space, then retry.",
                format!("{} -> {}", shaders_src.display(), shaders_dest.display()),
                source,
            )
        })?;

        // Make writable
        let _ = Command::new("chmod")
            .args(["-R", "u+w", &shaders_dest.to_string_lossy()])
            .output();
    }

    // Run the shader build script if it exists
    let build_script = shaders_src.join("build_shaders.nu");
    if build_script.exists() {
        let build_script_name = build_script
            .file_name()
            .map(|s| s.to_string_lossy().into_owned())
            .unwrap_or_else(|| "build_shaders.nu".to_string());
        let output = Command::new("nu")
            .arg(&build_script_name)
            .arg(glow_level)
            .arg(&shaders_dest)
            .arg(effect_color_literal)
            .arg(format_ghostty_trail_duration(trail_duration))
            .current_dir(&shaders_src)
            .output()
            .map_err(|source| {
                CoreError::io(
                    "run_ghostty_shader_build",
                    "Failed to run Ghostty shader build script",
                    "Ensure Nushell is installed and accessible on PATH.",
                    build_script.to_string_lossy(),
                    source,
                )
            })?;

        if !output.status.success() {
            let stderr = String::from_utf8_lossy(&output.stderr);
            return Err(CoreError::classified(
                ErrorClass::Runtime,
                "ghostty_shader_build_failed",
                format!("Ghostty shader build script failed: {}", stderr.trim()),
                "Check the shader build script for errors and retry.",
                serde_json::json!({"script": build_script.to_string_lossy()}),
            ));
        }
    }

    write_data_driven_cursor_shaders(&shaders_dest, registry, glow_level, trail_duration)?;

    Ok(true)
}

fn write_data_driven_cursor_shaders(
    shaders_dest: &Path,
    registry: &CursorRegistry,
    glow_level: &str,
    trail_duration: f64,
) -> Result<(), CoreError> {
    let data_driven = registry
        .enabled_definitions()
        .into_iter()
        .filter(|definition| {
            matches!(
                definition.family,
                CursorFamily::SimpleDual
                    | CursorFamily::AxisGradient
                    | CursorFamily::VerticalSplit
                    | CursorFamily::HorizontalSplit
            )
        })
        .collect::<Vec<_>>();
    if data_driven.is_empty() {
        return Ok(());
    }

    let common_path = shaders_dest.join("cursor_trail_common.glsl");
    let common = fs::read_to_string(&common_path).map_err(|source| {
        CoreError::io(
            "read_ghostty_shader_common",
            "Could not read the copied Ghostty cursor shader common library",
            "Reinstall Yazelix so the runtime includes configs/terminal_emulators/ghostty/shaders/cursor_trail_common.glsl.",
            common_path.to_string_lossy(),
            source,
        )
    })?;
    let glow_header = render_trail_glow_header(glow_level);

    for definition in data_driven {
        let output_path = shaders_dest.join(format!("cursor_trail_{}.glsl", definition.name));
        let rendered = format!(
            "{}{}\n{}",
            glow_header,
            common,
            render_data_driven_cursor_variant(definition, trail_duration)
        );
        fs::write(&output_path, rendered).map_err(|source| {
            CoreError::io(
                "write_data_driven_cursor_shader",
                "Could not write generated Ghostty cursor shader",
                "Check permissions for the Yazelix state directory and retry.",
                output_path.to_string_lossy(),
                source,
            )
        })?;
    }

    Ok(())
}

fn render_data_driven_cursor_variant(definition: &CursorDefinition, duration_scale: f64) -> String {
    let color_0 = definition.colors[0].glsl_vec4();
    let color_1 = definition.colors[1].glsl_vec4();
    match definition.family {
        CursorFamily::SimpleDual => {
            let duration = format_ghostty_trail_duration(0.25 * duration_scale);
            format!(
                r#"// Generated Yazelix simple-dual cursor variant

const vec4 YAZELIX_CURSOR_COLOR_0 = {color_0};
const vec4 YAZELIX_CURSOR_COLOR_1 = {color_1};
const float DURATION = {duration};

void mainImage(out vec4 fragColor, in vec2 fragCoord)
{{
    renderSimpleDualColorTrail(fragColor, fragCoord, YAZELIX_CURSOR_COLOR_0, YAZELIX_CURSOR_COLOR_1, DURATION, .007, 1.5);
}}
"#
            )
        }
        CursorFamily::AxisGradient => {
            let duration = format_ghostty_trail_duration(0.24 * duration_scale);
            format!(
                r#"// Generated Yazelix axis-gradient cursor variant

const vec4 YAZELIX_CURSOR_COLOR_0 = {color_0};
const vec4 YAZELIX_CURSOR_COLOR_1 = {color_1};
const float DURATION = {duration};

void mainImage(out vec4 fragColor, in vec2 fragCoord)
{{
    renderAxisGradientTrail(fragColor, fragCoord, YAZELIX_CURSOR_COLOR_0, YAZELIX_CURSOR_COLOR_1, DURATION, 1.6, 0.42, 0.30, 0.5);
}}
"#
            )
        }
        CursorFamily::VerticalSplit => {
            let duration = format_ghostty_trail_duration(0.24 * duration_scale);
            format!(
                r#"// Generated Yazelix vertical-split cursor variant

const vec4 YAZELIX_CURSOR_COLOR_0 = {color_0};
const vec4 YAZELIX_CURSOR_COLOR_1 = {color_1};
const float DURATION = {duration};

void mainImage(out vec4 fragColor, in vec2 fragCoord)
{{
    renderVerticalSplitTrail(fragColor, fragCoord, YAZELIX_CURSOR_COLOR_0, YAZELIX_CURSOR_COLOR_1, DURATION, 1.8);
}}
"#
            )
        }
        CursorFamily::HorizontalSplit => {
            let duration = format_ghostty_trail_duration(0.24 * duration_scale);
            format!(
                r#"// Generated Yazelix horizontal-split cursor variant

const vec4 YAZELIX_CURSOR_COLOR_0 = {color_0};
const vec4 YAZELIX_CURSOR_COLOR_1 = {color_1};
const float DURATION = {duration};

void mainImage(out vec4 fragColor, in vec2 fragCoord)
{{
    renderHorizontalSplitTrail(fragColor, fragCoord, YAZELIX_CURSOR_COLOR_0, YAZELIX_CURSOR_COLOR_1, DURATION, 1.6);
}}
"#
            )
        }
        CursorFamily::CuratedTemplate => String::new(),
    }
}

fn render_trail_glow_header(glow_level: &str) -> String {
    let profile = glow_profile(glow_level);
    format!(
        r#"// Generated by Yazelix with cursor glow = {glow_level}
const float YAZELIX_TRAIL_GLOW_STRENGTH = {};
const float YAZELIX_TRAIL_GLOW_WIDTH_SCALE = {};
const float YAZELIX_CURSOR_GLOW_STRENGTH = {};
const float YAZELIX_CURSOR_GLOW_WIDTH_SCALE = {};
const float YAZELIX_TRAIL_EDGE_WIDTH_SCALE = {};
const float YAZELIX_CURSOR_EDGE_WIDTH_SCALE = {};
const float YAZELIX_TRAIL_CORE_OFFSET_SCALE = {};

"#,
        profile.trail_glow_strength,
        profile.trail_glow_width_scale,
        profile.cursor_glow_strength,
        profile.cursor_glow_width_scale,
        profile.trail_edge_width_scale,
        profile.cursor_edge_width_scale,
        profile.trail_core_offset_scale,
    )
}

struct GlowProfile {
    trail_glow_strength: &'static str,
    cursor_glow_strength: &'static str,
    trail_edge_width_scale: &'static str,
    cursor_edge_width_scale: &'static str,
    trail_core_offset_scale: &'static str,
    trail_glow_width_scale: &'static str,
    cursor_glow_width_scale: &'static str,
}

fn glow_profile(glow_level: &str) -> GlowProfile {
    match glow_level {
        "none" => GlowProfile {
            trail_glow_strength: "0.0",
            cursor_glow_strength: "0.0",
            trail_edge_width_scale: "0.0",
            cursor_edge_width_scale: "0.0",
            trail_core_offset_scale: "0.0",
            trail_glow_width_scale: "1.0",
            cursor_glow_width_scale: "1.0",
        },
        "low" => GlowProfile {
            trail_glow_strength: "1.0",
            cursor_glow_strength: "1.0",
            trail_edge_width_scale: "1.0",
            cursor_edge_width_scale: "1.0",
            trail_core_offset_scale: "1.0",
            trail_glow_width_scale: "0.55",
            cursor_glow_width_scale: "0.6",
        },
        "high" => GlowProfile {
            trail_glow_strength: "1.0",
            cursor_glow_strength: "1.0",
            trail_edge_width_scale: "1.0",
            cursor_edge_width_scale: "1.0",
            trail_core_offset_scale: "1.0",
            trail_glow_width_scale: "1.7",
            cursor_glow_width_scale: "1.6",
        },
        _ => GlowProfile {
            trail_glow_strength: "1.0",
            cursor_glow_strength: "1.0",
            trail_edge_width_scale: "1.0",
            cursor_edge_width_scale: "1.0",
            trail_core_offset_scale: "1.0",
            trail_glow_width_scale: "1.0",
            cursor_glow_width_scale: "1.0",
        },
    }
}

fn copy_dir_all(src: impl AsRef<Path>, dst: impl AsRef<Path>) -> std::io::Result<()> {
    fs::create_dir_all(&dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let ty = entry.file_type()?;
        let src_path = entry.path();
        let dst_path = dst.as_ref().join(entry.file_name());
        if ty.is_dir() {
            copy_dir_all(&src_path, &dst_path)?;
        } else {
            fs::copy(&src_path, &dst_path)?;
        }
    }
    Ok(())
}

pub fn generate_ghostty_materialization(
    request: &GhosttyMaterializationRequest,
) -> Result<GhosttyMaterializationData, CoreError> {
    let registry = CursorRegistry::load(&request.cursor_config_path)?;
    let registry_state = registry.resolve();
    validate_ghostty_trail_duration(registry_state.duration)?;
    let cursor_state = build_ghostty_cursor_render_state(&registry_state);

    let ghostty_dir = request
        .state_dir
        .join("configs")
        .join("terminal_emulators")
        .join("ghostty");

    fs::create_dir_all(&ghostty_dir).map_err(|source| {
        CoreError::io(
            "create_ghostty_output_dir",
            "Could not create the managed Ghostty output directory",
            "Check permissions for the Yazelix state directory and retry.",
            ghostty_dir.to_string_lossy(),
            source,
        )
    })?;

    let config_content = build_ghostty_config(request, &cursor_state, &registry_state);
    let generated_path = ghostty_dir.join("config");

    fs::write(&generated_path, config_content).map_err(|source| {
        CoreError::io(
            "write_ghostty_config",
            "Could not write the managed Ghostty config",
            "Check permissions for the Yazelix state directory and retry.",
            generated_path.to_string_lossy(),
            source,
        )
    })?;

    let shaders_synced = sync_ghostty_shader_assets(
        &request.runtime_dir,
        &ghostty_dir,
        &registry_state.glow,
        &cursor_state.effect_color_literal,
        registry_state.duration,
        &registry,
    )?;

    Ok(GhosttyMaterializationData {
        generated_path: generated_path.to_string_lossy().into_owned(),
        cursor_state,
        shaders_synced,
    })
}
