# Materializes the reviewed Codex config and rules inputs into generated files.
#
# Authorship contract (YZXCONV-004):
#   editable input : ~/.config/yazelix/agents/codex/config.toml.src (deploy surface)
#   review copy    : agent_configs/codex/config.toml.src (this repo)
#   rules input    : ~/.config/yazelix/agents/codex/RULES.md.src
#   rules review   : agent_configs/codex/RULES.md.src
#   generated out  : $CODEX_HOME/config.toml and $CODEX_HOME/RULES.md — both
#                    completed before rollback-assisted publication
#
# The runtime/state home stays CODEX_HOME=/home/flexnetos/.codex; auth.json,
# sessions/, and *.sqlite* are runtime state and are never touched here.
#
# Fail-closed validation: the input must be valid TOML and must not reference
# the retired /home/flexnetos/FlexNetOS workspace mirror, raw /nix/store pins,
# Nix profile-generation paths, or user-local binaries — ~/.nix-profile is the
# sole binary selector.

const CONFIG_GENERATED_MARKER = "GENERATED by yazelix codex config materializer"
const RULES_GENERATED_MARKER = "GENERATED by yazelix codex rules materializer"
const CANONICAL_CONFIG_INPUT = "~/.config/yazelix/agents/codex/config.toml.src"
const CANONICAL_RULES_INPUT = "~/.config/yazelix/agents/codex/RULES.md.src"
const TRANSACTION_SCHEMA = "yazelix.codex-config-transaction.v1"
const TRANSACTION_JOURNAL = ".yazelix-codex-transaction.json"
const PROFILE_ICM = "/home/flexnetos/.nix-profile/bin/icm"
const FORBIDDEN_PATHS = [
    "/home/flexnetos/FlexNetOS"            # retired workspace mirror
    "/nix/store/"                          # raw store pin bypasses the profile selector
    "/nix/var/nix/profiles/"               # system profile-generation pin
    ".local/state/nix/profiles/profile-"   # user profile-generation pin
    ".local/bin"                            # absolute, tilde, or variable user-local shadow
]

def fail [message: string] {
    print --stderr $"codex config materializer: ($message)"
    exit 1
}

def remove-if-present [target: path] {
    if ($target | path exists) {
        rm --force $target
    }
}

def transaction-paths [directory: path, token: string] {
    {
        config_stage: ($directory | path join $".config.toml.yazelix-stage-($token)")
        rules_stage: ($directory | path join $".RULES.md.yazelix-stage-($token)")
        config_backup: ($directory | path join $".config.toml.yazelix-backup-($token)")
        rules_backup: ($directory | path join $".RULES.md.yazelix-backup-($token)")
    }
}

def recover-transaction [journal: path, config_out: path, rules_out: path] {
    if not ($journal | path exists) { return false }
    let transaction = (try { open --raw $journal | from json } catch {
        fail $"pending transaction journal is invalid: ($journal)"
    })
    let directory = ($config_out | path dirname | path expand)
    let valid = (
        ($transaction.schema? | default "") == $TRANSACTION_SCHEMA
        and ($transaction.token? | default "") =~ '^[0-9a-f-]+$'
        and ($transaction.config_name? | default "") == ($config_out | path basename)
        and ($transaction.rules_name? | default "") == ($rules_out | path basename)
        and (($transaction.had_config? | describe) == "bool")
        and (($transaction.had_rules? | describe) == "bool")
    )
    if not $valid {
        fail $"pending transaction journal does not match requested outputs: ($journal)"
    }
    let paths = (transaction-paths $directory $transaction.token)
    if $transaction.had_config {
        if ($paths.config_backup | path exists) {
            mv --force $paths.config_backup $config_out
        }
    } else {
        remove-if-present $config_out
    }
    if $transaction.had_rules {
        if ($paths.rules_backup | path exists) {
            mv --force $paths.rules_backup $rules_out
        }
    } else {
        remove-if-present $rules_out
    }
    for artifact in [
        $paths.config_stage
        $paths.rules_stage
        $paths.config_backup
        $paths.rules_backup
    ] {
        remove-if-present $artifact
    }
    remove-if-present $journal
    do { ^sync -f $directory } | complete | ignore
    print $"recovered prior Codex config/rules generation from ($journal)"
    true
}

def main [
    config_src: path
    config_out: path
    rules_src: path
    rules_out: path
    --recover-only
] {
    if $config_out == $rules_out {
        fail "config and rules outputs must be different files"
    }
    for output in [$config_out $rules_out] {
        if ($output | path exists) and (($output | path type) == "dir") {
            fail $"output path is a directory: ($output)"
        }
    }
    let config_dir = ($config_out | path dirname | path expand)
    let rules_dir = ($rules_out | path dirname | path expand)
    if $config_dir != $rules_dir {
        fail "config and rules outputs must share one directory for coordinated publication"
    }
    mkdir $config_dir
    let journal = ($config_dir | path join $TRANSACTION_JOURNAL)
    let recovered = (recover-transaction $journal $config_out $rules_out)
    if $recover_only {
        if not $recovered { print "no pending Codex config/rules transaction" }
        return
    }

    if not ($config_src | path exists) {
        fail $"config input not found: ($config_src)"
    }
    if not ($rules_src | path exists) {
        fail $"rules input not found: ($rules_src)"
    }

    let config_raw = (open --raw $config_src)
    let config_declared = (try { $config_raw | from toml } catch {
        fail $"config input is not valid TOML: ($config_src)"
    })
    for pattern in $FORBIDDEN_PATHS {
        if ($config_raw | str contains $pattern) {
            fail $"config input references forbidden path ($pattern): ($config_src)"
        }
    }
    let icm_command = ($config_declared.mcp_servers?.icm?.command? | default "")
    if $icm_command != $PROFILE_ICM {
        fail $"reviewed ICM command must be the exact profile selector ($PROFILE_ICM)"
    }

    let rules_raw = (open --raw $rules_src)
    if not ($rules_raw | str starts-with "# FlexNetOS Codex Durable Rules\n") {
        fail $"rules input must start with the durable rules heading: ($rules_src)"
    }
    if ($rules_raw | str contains $RULES_GENERATED_MARKER) {
        fail $"rules input contains a generated-output marker: ($rules_src)"
    }

    # The reviewed source owns every top-level key/table that it declares.
    # Live-only top-level tables are runtime state and survive a cutover. This
    # keeps Codex-managed hook trust state without allowing a stale live table
    # (for example projects or MCP servers) to override its reviewed owner.
    let prior_config = if ($config_out | path exists) {
        let prior_raw = (open --raw $config_out)
        try { $prior_raw | from toml } catch {
            fail $"existing config output is not valid TOML: ($config_out)"
        }
    } else { {} }
    let source_keys = ($config_declared | columns)
    let prior_keys = ($prior_config | columns)
    let replaced_keys = ($source_keys | where {|key| $key in $prior_keys })
    let runtime_projection = if ($replaced_keys | is-empty) {
        $prior_config
    } else {
        $prior_config | reject ...$replaced_keys
    }
    let runtime_projection_raw = ($runtime_projection | to toml)
    let runtime_projection_hash = ($runtime_projection_raw | hash sha256)
    let merged_config = ($runtime_projection | merge $config_declared)
    let merged_config_raw = ($merged_config | to toml)
    for pattern in $FORBIDDEN_PATHS {
        if ($merged_config_raw | str contains $pattern) {
            fail $"materialized config would retain forbidden path ($pattern): ($config_out)"
        }
    }

    let config_hash = ($config_raw | hash sha256)
    let rules_hash = ($rules_raw | hash sha256)
    let config_header = [
        $"# ($CONFIG_GENERATED_MARKER) — do not hand-edit."
        $"# authorship input: ($CANONICAL_CONFIG_INPUT)"
        $"# source_sha256 = ($config_hash)"
        $"# runtime_projection_sha256 = ($runtime_projection_hash)"
        ""
    ]
    let rules_header = [
        $"<!-- ($RULES_GENERATED_MARKER) — do not hand-edit. -->"
        $"<!-- authorship input: ($CANONICAL_RULES_INPUT) -->"
        $"<!-- source_sha256 = ($rules_hash) -->"
        ""
    ]

    let token = (random uuid)
    let paths = (transaction-paths $config_dir $token)
    let config_stage = $paths.config_stage
    let rules_stage = $paths.rules_stage
    let config_backup = $paths.config_backup
    let rules_backup = $paths.rules_backup
    let config_rendered = (($config_header | str join "\n") + $merged_config_raw)
    let rules_rendered = (($rules_header | str join "\n") + $rules_raw)
    let had_config = ($config_out | path exists)
    let had_rules = ($rules_out | path exists)
    let transaction = {
        schema: $TRANSACTION_SCHEMA
        token: $token
        config_name: ($config_out | path basename)
        rules_name: ($rules_out | path basename)
        had_config: $had_config
        had_rules: $had_rules
    }
    try {
        $transaction | to json --indent 2 | save --raw $journal
    } catch {|error|
        fail $"unable to write transaction journal: ($error.msg)"
    }
    let journal_sync = (do { ^sync -f $config_dir } | complete)
    if $journal_sync.exit_code != 0 {
        remove-if-present $journal
        fail $"unable to persist transaction journal: ($journal_sync.stderr | str trim)"
    }

    # Prepare both complete files before changing either live output. A staging
    # failure therefore leaves the previous generation byte-for-byte intact.
    try {
        $config_rendered | save --raw $config_stage
        $rules_rendered | save --raw $rules_stage
    } catch {|error|
        remove-if-present $config_stage
        remove-if-present $rules_stage
        remove-if-present $journal
        fail $"unable to stage output pair: ($error.msg)"
    }
    for staged in [$config_stage $rules_stage] {
        let mode = (do { ^chmod 0644 $staged } | complete)
        if $mode.exit_code != 0 {
            remove-if-present $config_stage
            remove-if-present $rules_stage
            remove-if-present $journal
            fail $"unable to set generated output mode 0644: ($staged)"
        }
    }

    try {
        if $had_config { cp $config_out $config_backup }
        if $had_rules { cp $rules_out $rules_backup }
    } catch {|error|
        remove-if-present $config_stage
        remove-if-present $rules_stage
        remove-if-present $config_backup
        remove-if-present $rules_backup
        remove-if-present $journal
        fail $"unable to stage rollback copies: ($error.msg)"
    }

    try {
        mv --force $config_stage $config_out
    } catch {|error|
        remove-if-present $config_stage
        remove-if-present $rules_stage
        remove-if-present $config_backup
        remove-if-present $rules_backup
        remove-if-present $journal
        fail $"unable to replace config output: ($error.msg)"
    }
    if (($env.YAZELIX_TEST_CRASH_AFTER_CONFIG_REPLACE? | default "") == "1") {
        print --stderr "codex config materializer: injected interruption after config replacement"
        exit 86
    }
    # POSIX cannot publish two independent pathnames with one rename. Keep the
    # contract honest: publication uses a durable recovery journal and rollback
    # copies, but is not described as a two-path atomic rename.
    try {
        mv --force $rules_stage $rules_out
    } catch {|error|
        if $had_config {
            mv --force $config_backup $config_out
        } else {
            remove-if-present $config_out
        }
        if $had_rules {
            if ($rules_backup | path exists) {
                mv --force $rules_backup $rules_out
            }
        } else {
            remove-if-present $rules_out
        }
        remove-if-present $rules_stage
        remove-if-present $config_backup
        remove-if-present $rules_backup
        remove-if-present $journal
        fail $"unable to replace rules output; config was rolled back: ($error.msg)"
    }
    remove-if-present $journal
    do { ^sync -f $config_dir } | complete | ignore
    remove-if-present $config_backup
    remove-if-present $rules_backup

    print $"ok materialized ($config_out) source_sha256=($config_hash)"
    print $"ok materialized ($rules_out) source_sha256=($rules_hash)"
}
