# Materializes the reviewed Codex config input into a generated config.toml
#
# Authorship contract (YZXCONV-004):
#   editable input : ~/.config/yazelix/agents/codex/config.toml.src (deploy surface)
#   review copy    : agent_configs/codex/config.toml.src (this repo)
#   generated out  : $CODEX_HOME/config.toml — written only at an approved
#                    cutover with a checksum-backed backup of the prior file
#
# The runtime/state home stays CODEX_HOME=/home/flexnetos/.codex; auth.json,
# sessions/, and *.sqlite* are runtime state and are never touched here.
#
# Fail-closed validation: the input must be valid TOML and must not reference
# the retired /home/flexnetos/FlexNetOS workspace mirror, raw /nix/store pins,
# or Nix profile-generation paths — ~/.nix-profile is the sole binary selector.

const GENERATED_MARKER = "GENERATED by yazelix codex config materializer"
const CANONICAL_INPUT = "~/.config/yazelix/agents/codex/config.toml.src"
const FORBIDDEN_PATHS = [
    "/home/flexnetos/FlexNetOS"            # retired workspace mirror
    "/nix/store/"                          # raw store pin bypasses the profile selector
    "/nix/var/nix/profiles/"               # system profile-generation pin
    ".local/state/nix/profiles/profile-"   # user profile-generation pin
]

def fail [message: string] {
    print --stderr $"codex config materializer: ($message)"
    exit 1
}

def main [src: path, out: path] {
    if not ($src | path exists) {
        fail $"input not found: ($src)"
    }
    let raw = (open --raw $src)
    try { $raw | from toml | ignore } catch {
        fail $"input is not valid TOML: ($src)"
    }
    for pattern in $FORBIDDEN_PATHS {
        if ($raw | str contains $pattern) {
            fail $"input references forbidden path ($pattern): ($src)"
        }
    }
    let src_hash = ($raw | hash sha256)
    let header = [
        $"# ($GENERATED_MARKER) — do not hand-edit."
        $"# authorship input: ($CANONICAL_INPUT)"
        $"# source_sha256 = ($src_hash)"
        ""
    ]
    mkdir ($out | path dirname)
    (($header | str join "\n") + $raw) | save --force --raw $out
    print $"ok materialized ($out) source_sha256=($src_hash)"
}
