# FlexNetOS/Yazelix strict local-build policy.
# This file is installed by the profile-owned yazelix_host_policy command.

always-allow-substitutes = false
compress-build-log = false
eval-cores = 0
extra-experimental-features = nix-command flakes
flake-registry =
keep-build-log = false
lazy-trees = true
max-jobs = auto
substitute = false
substituters =
trusted-public-keys =
trusted-substituters =
use-xdg-base-directories = true

!include nix.custom.conf
