// Test lane: maintainer

use assert_cmd::Command;
use serde_json::Value;
use std::fs;
use tempfile::TempDir;

// Defends: yzx_core owns public command metadata for migrated Rust-only leaves instead of requiring Nushell scope probing.
// Strength: defect=2 behavior=2 resilience=2 cost=1 uniqueness=2 total=9/10
#[test]
fn command_metadata_externs_include_rust_only_leaves_once() {
    let output = Command::cargo_bin("yzx_core")
        .unwrap()
        .arg("yzx-command-metadata.externs")
        .output()
        .unwrap();

    assert!(output.status.success());
    assert!(output.stderr.is_empty());

    let envelope: Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(envelope["command"], "yzx-command-metadata.externs");
    assert_eq!(envelope["status"], "ok");

    let extern_content = envelope["data"]["extern_content"].as_str().unwrap();
    assert_eq!(
        extern_content.matches("export extern \"yzx env\"").count(),
        1
    );
    assert_eq!(
        extern_content.matches("export extern \"yzx run\"").count(),
        1
    );
    assert_eq!(
        extern_content
            .matches("export extern \"yzx update nix\"")
            .count(),
        1
    );
    assert!(
        extern_content.contains("# Generated by Yazelix from Rust-owned yzx command metadata.")
    );
    assert!(extern_content.contains("--no-shell(-n)"));
    assert!(extern_content.contains("export extern \"yzx config\""));
    assert!(extern_content.contains("export extern \"yzx config set\""));
    assert!(extern_content.contains("export extern \"yzx config unset\""));
    assert!(extern_content.contains("export extern \"yzx doctor\""));
    assert!(extern_content.contains("export extern \"yzx keys\""));
    assert!(extern_content.contains("export extern \"yzx keys helix\""));
    assert!(extern_content.contains("export extern \"yzx reveal\""));
    assert!(extern_content.contains("export extern \"yzx sponsor\""));
    assert!(extern_content.contains("export extern \"yzx warp\""));
    assert!(extern_content.contains("export extern \"yzx why\""));
    assert!(extern_content.contains("--kill(-k)"));
    assert!(extern_content.contains("--path"));
    assert!(extern_content.contains("--with"));
    assert!(extern_content.contains("--yes"));
    assert!(extern_content.contains("--no-backup"));
    assert!(extern_content.contains("...argv: string"));
    assert!(!extern_content.contains(": settings.path"));
    assert!(!extern_content.contains(": json"));
    assert!(!extern_content.contains(": key=value"));
}

// Defends: root yzx help can be served without evaluating the Nushell command tree.
// Strength: defect=2 behavior=2 resilience=1 cost=1 uniqueness=2 total=8/10
#[test]
fn command_metadata_help_prints_public_yzx_surface() {
    let output = Command::cargo_bin("yzx_core")
        .unwrap()
        .arg("yzx-command-metadata.help")
        .output()
        .unwrap();

    assert!(output.status.success());
    assert!(output.stderr.is_empty());

    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("Commands:"));
    assert!(stdout.contains("yzx config"));
    assert!(stdout.contains("yzx doctor"));
    assert!(stdout.contains("yzx env"));
    assert!(stdout.contains("yzx keys"));
    assert!(stdout.contains("yzx reveal"));
    assert!(stdout.contains("yzx run"));
    assert!(stdout.contains("yzx sponsor"));
    assert!(stdout.contains("yzx warp"));
    assert!(stdout.contains("yzx why"));
    assert!(stdout.contains("yzx update nix"));
}

// Regression: yzx_core owns generated extern bridge sync, so startup no longer needs the Nushell compatibility wrapper.
// Strength: defect=2 behavior=2 resilience=2 cost=1 uniqueness=2 total=9/10
#[test]
fn command_metadata_sync_externs_writes_generated_bridge() {
    let runtime = TempDir::new().unwrap();
    let state = TempDir::new().unwrap();
    fs::write(runtime.path().join("yazelix_default.toml"), "").unwrap();

    let first = Command::cargo_bin("yzx_core")
        .unwrap()
        .arg("yzx-command-metadata.sync-externs")
        .arg("--runtime-dir")
        .arg(runtime.path())
        .arg("--state-dir")
        .arg(state.path())
        .output()
        .unwrap();

    assert!(first.status.success());
    assert!(first.stderr.is_empty());

    let envelope: Value = serde_json::from_slice(&first.stdout).unwrap();
    assert_eq!(envelope["command"], "yzx-command-metadata.sync-externs");
    assert_eq!(envelope["status"], "ok");
    assert_eq!(envelope["data"]["status"], "updated");

    let extern_path = envelope["data"]["extern_path"].as_str().unwrap();
    let fingerprint_path = envelope["data"]["fingerprint_path"].as_str().unwrap();
    let generated = fs::read_to_string(extern_path).unwrap();
    assert!(generated.contains("export extern \"yzx env\""));
    assert!(generated.contains("export extern \"yzx run\""));
    assert!(fs::metadata(fingerprint_path).unwrap().is_file());
}

// Regression: Rust-owned extern bridge sync ignores host Nushell config so migrated leaves do not get rendered twice on startup.
// Strength: defect=2 behavior=2 resilience=2 cost=1 uniqueness=2 total=9/10
#[test]
fn command_metadata_sync_externs_ignores_host_nushell_config() {
    let runtime = TempDir::new().unwrap();
    let state = TempDir::new().unwrap();
    let home = TempDir::new().unwrap();
    let xdg_config_home = home.path().join(".config");
    let nushell_config_dir = xdg_config_home.join("nushell");
    let initializers_dir = state.path().join("initializers").join("nushell");
    fs::create_dir_all(&nushell_config_dir).unwrap();
    fs::create_dir_all(&initializers_dir).unwrap();
    fs::write(runtime.path().join("yazelix_default.toml"), "").unwrap();
    fs::write(initializers_dir.join("yazelix_init.nu"), "").unwrap();
    fs::write(initializers_dir.join("yazelix_user_hook.nu"), "").unwrap();

    let sync_output = Command::cargo_bin("yzx_core")
        .unwrap()
        .arg("yzx-command-metadata.sync-externs")
        .arg("--runtime-dir")
        .arg(runtime.path())
        .arg("--state-dir")
        .arg(state.path())
        .output()
        .unwrap();

    assert!(sync_output.status.success());
    let envelope: Value = serde_json::from_slice(&sync_output.stdout).unwrap();
    let extern_path = envelope["data"]["extern_path"].as_str().unwrap();
    fs::write(
        nushell_config_dir.join("config.nu"),
        format!("source \"{extern_path}\"\n"),
    )
    .unwrap();

    let second_sync = Command::cargo_bin("yzx_core")
        .unwrap()
        .env("HOME", home.path())
        .env("XDG_CONFIG_HOME", &xdg_config_home)
        .arg("yzx-command-metadata.sync-externs")
        .arg("--runtime-dir")
        .arg(runtime.path())
        .arg("--state-dir")
        .arg(state.path())
        .output()
        .unwrap();

    assert!(
        second_sync.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&second_sync.stderr)
    );
    let generated = fs::read_to_string(extern_path).unwrap();
    assert_eq!(generated.matches("export extern \"yzx env\"").count(), 1);
    assert_eq!(generated.matches("export extern \"yzx run\"").count(), 1);
}
