// Test lane: maintainer

use assert_cmd::Command;
use serde_json::Value;

// Defends: yzx_core owns public command metadata for migrated Rust-only leaves instead of requiring Nushell scope probing.
// Strength: defect=2 behavior=2 resilience=2 cost=1 uniqueness=2 total=9/10
#[test]
fn command_metadata_externs_include_rust_only_leaves_once() {
    let output = Command::cargo_bin("yzx_core")
        .unwrap()
        .arg("yzx-command-metadata.externs")
        .output()
        .unwrap();

    assert!(output.status.success());
    assert!(output.stderr.is_empty());

    let envelope: Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(envelope["command"], "yzx-command-metadata.externs");
    assert_eq!(envelope["status"], "ok");

    let extern_content = envelope["data"]["extern_content"].as_str().unwrap();
    assert_eq!(
        extern_content.matches("export extern \"yzx env\"").count(),
        1
    );
    assert_eq!(
        extern_content.matches("export extern \"yzx run\"").count(),
        1
    );
    assert_eq!(
        extern_content
            .matches("export extern \"yzx update nix\"")
            .count(),
        1
    );
    assert!(
        extern_content.contains("# Generated by Yazelix from Rust-owned yzx command metadata.")
    );
    assert!(extern_content.contains("--no-shell(-n)"));
    assert!(extern_content.contains("...argv: string"));
}

// Defends: root yzx help can be served without evaluating the Nushell command tree.
// Strength: defect=2 behavior=2 resilience=1 cost=1 uniqueness=2 total=8/10
#[test]
fn command_metadata_help_prints_public_yzx_surface() {
    let output = Command::cargo_bin("yzx_core")
        .unwrap()
        .arg("yzx-command-metadata.help")
        .output()
        .unwrap();

    assert!(output.status.success());
    assert!(output.stderr.is_empty());

    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("Commands:"));
    assert!(stdout.contains("yzx env"));
    assert!(stdout.contains("yzx run"));
    assert!(stdout.contains("yzx update nix"));
}
