// Test lane: maintainer

use assert_cmd::Command;
use serde_json::Value;
use std::fs;
use tempfile::TempDir;

// Defends: yzx_core owns public command metadata for migrated Rust-only leaves instead of requiring Nushell scope probing.
// Strength: defect=2 behavior=2 resilience=2 cost=1 uniqueness=2 total=9/10
#[test]
fn command_metadata_externs_include_rust_only_leaves_once() {
    let output = Command::cargo_bin("yzx_core")
        .unwrap()
        .arg("yzx-command-metadata.externs")
        .output()
        .unwrap();

    assert!(output.status.success());
    assert!(output.stderr.is_empty());

    let envelope: Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(envelope["command"], "yzx-command-metadata.externs");
    assert_eq!(envelope["status"], "ok");

    let extern_content = envelope["data"]["extern_content"].as_str().unwrap();
    assert_eq!(
        extern_content.matches("export extern \"yzx env\"").count(),
        1
    );
    assert_eq!(
        extern_content.matches("export extern \"yzx run\"").count(),
        1
    );
    assert_eq!(
        extern_content
            .matches("export extern \"yzx update nix\"")
            .count(),
        1
    );
    assert!(
        extern_content.contains("# Generated by Yazelix from Rust-owned yzx command metadata.")
    );
    assert!(extern_content.contains("--no-shell(-n)"));
    assert!(extern_content.contains("export extern \"yzx config\""));
    assert!(extern_content.contains("export extern \"yzx cwd\""));
    assert!(extern_content.contains("export extern \"yzx doctor\""));
    assert!(extern_content.contains("export extern \"yzx keys\""));
    assert!(extern_content.contains("export extern \"yzx keys helix\""));
    assert!(extern_content.contains("export extern \"yzx reveal\""));
    assert!(extern_content.contains("export extern \"yzx sponsor\""));
    assert!(extern_content.contains("export extern \"yzx why\""));
    assert!(extern_content.contains("--path"));
    assert!(extern_content.contains("--yes"));
    assert!(extern_content.contains("--no-backup"));
    assert!(extern_content.contains("...argv: string"));
}

// Defends: root yzx help can be served without evaluating the Nushell command tree.
// Strength: defect=2 behavior=2 resilience=1 cost=1 uniqueness=2 total=8/10
#[test]
fn command_metadata_help_prints_public_yzx_surface() {
    let output = Command::cargo_bin("yzx_core")
        .unwrap()
        .arg("yzx-command-metadata.help")
        .output()
        .unwrap();

    assert!(output.status.success());
    assert!(output.stderr.is_empty());

    let stdout = String::from_utf8(output.stdout).unwrap();
    assert!(stdout.contains("Commands:"));
    assert!(stdout.contains("yzx config"));
    assert!(stdout.contains("yzx cwd"));
    assert!(stdout.contains("yzx doctor"));
    assert!(stdout.contains("yzx env"));
    assert!(stdout.contains("yzx keys"));
    assert!(stdout.contains("yzx reveal"));
    assert!(stdout.contains("yzx run"));
    assert!(stdout.contains("yzx sponsor"));
    assert!(stdout.contains("yzx why"));
    assert!(stdout.contains("yzx update nix"));
}

// Regression: yzx_core owns generated extern bridge sync, so startup no longer needs the Nushell compatibility wrapper.
// Strength: defect=2 behavior=2 resilience=2 cost=1 uniqueness=2 total=9/10
#[test]
fn command_metadata_sync_externs_writes_generated_bridge() {
    let runtime = TempDir::new().unwrap();
    let state = TempDir::new().unwrap();
    fs::write(runtime.path().join("yazelix_default.toml"), "").unwrap();

    let first = Command::cargo_bin("yzx_core")
        .unwrap()
        .arg("yzx-command-metadata.sync-externs")
        .arg("--runtime-dir")
        .arg(runtime.path())
        .arg("--state-dir")
        .arg(state.path())
        .output()
        .unwrap();

    assert!(first.status.success());
    assert!(first.stderr.is_empty());

    let envelope: Value = serde_json::from_slice(&first.stdout).unwrap();
    assert_eq!(envelope["command"], "yzx-command-metadata.sync-externs");
    assert_eq!(envelope["status"], "ok");
    assert_eq!(envelope["data"]["status"], "updated");

    let extern_path = envelope["data"]["extern_path"].as_str().unwrap();
    let fingerprint_path = envelope["data"]["fingerprint_path"].as_str().unwrap();
    let generated = fs::read_to_string(extern_path).unwrap();
    assert!(generated.contains("export extern \"yzx env\""));
    assert!(generated.contains("export extern \"yzx run\""));
    assert!(fs::metadata(fingerprint_path).unwrap().is_file());
}
