[[mgr.append_keymap]]
on = ["<A-z>"]
run = "plugin zoxide-editor"
desc = "Retarget tab workspace with zoxide"

[[mgr.append_keymap]]
on = ["<A-r>"]
run = 'shell "$YZX_YAZI_RETURN"'
desc = "Return from managed Yazi"
