os:
  edit: '$EDITOR -- {{filename}}'
  editAtLine: '$EDITOR -- {{filename}}:{{line}}'
  editAtLineAndWait: '$EDITOR -- {{filename}}:{{line}}'
  editInTerminal: true
  openDirInEditor: '$EDITOR -- {{dir}}'
