#!/bin/bash
# Yazelix-managed Bash startup. User hook: ~/.config/yazelix/shell_bash.sh
# This file is part of Yazelix and should be persisted in the repository.

YAZELIX_RUNTIME_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Define the directory where Yazelix generates individual initializer scripts.
# Using XDG-compliant state directory (not config directory)
YAZELIX_BASH_INITIALIZERS_DIR="$HOME/.local/share/yazelix/initializers/bash"

# Prefer the aggregate initializer if present (generated by Yazelix)
if [ -f "$YAZELIX_BASH_INITIALIZERS_DIR/yazelix_init.sh" ] && [ -s "$YAZELIX_BASH_INITIALIZERS_DIR/yazelix_init.sh" ]; then
  # shellcheck disable=SC1090
  source "$YAZELIX_BASH_INITIALIZERS_DIR/yazelix_init.sh"
else

# Source individual initializers if they exist and are non-empty.
if [ -f "$YAZELIX_BASH_INITIALIZERS_DIR/starship_init.sh" ] && [ -s "$YAZELIX_BASH_INITIALIZERS_DIR/starship_init.sh" ]; then
  source "$YAZELIX_BASH_INITIALIZERS_DIR/starship_init.sh"
fi

if [ -f "$YAZELIX_BASH_INITIALIZERS_DIR/zoxide_init.sh" ] && [ -s "$YAZELIX_BASH_INITIALIZERS_DIR/zoxide_init.sh" ]; then
  source "$YAZELIX_BASH_INITIALIZERS_DIR/zoxide_init.sh"
fi

# mise_init.sh is generated conditionally by the shellHook.
# Source it if it exists and is non-empty.
if [ -f "$YAZELIX_BASH_INITIALIZERS_DIR/mise_init.sh" ] && [ -s "$YAZELIX_BASH_INITIALIZERS_DIR/mise_init.sh" ]; then
  source "$YAZELIX_BASH_INITIALIZERS_DIR/mise_init.sh"
fi

fi

# Yazelix Aliases for Bash
alias yazelix="sh $YAZELIX_RUNTIME_DIR/shells/posix/yzx_cli.sh launch"
alias lg='lazygit'

# Note: yzx command is defined in ~/.bashrc (via v3 hooks) and is always available

if [ -n "${YAZELIX_CONFIG_DIR:-}" ]; then
  yazelix_bash_user_hook="$YAZELIX_CONFIG_DIR/shell_bash.sh"
else
  yazelix_bash_user_hook="$HOME/.config/yazelix/shell_bash.sh"
fi
if [ -f "$yazelix_bash_user_hook" ] && [ -s "$yazelix_bash_user_hook" ]; then
  # shellcheck disable=SC1090
  source "$yazelix_bash_user_hook"
fi

# Ensure this script doesn't produce output unless it's an error,
# as it's sourced by .bashrc.
