#!/bin/bash
# ~/.config/yazelix/shells/bash/yazelix_bash_config.sh
# This file is part of Yazelix and should be persisted in the repository.

YAZELIX_RUNTIME_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"

# Define the directory where Yazelix generates individual initializer scripts.
# Using XDG-compliant state directory (not config directory)
YAZELIX_BASH_INITIALIZERS_DIR="$HOME/.local/share/yazelix/initializers/bash"

# Prefer the aggregate initializer if present (generated by Yazelix)
if [ -f "$YAZELIX_BASH_INITIALIZERS_DIR/yazelix_init.sh" ] && [ -s "$YAZELIX_BASH_INITIALIZERS_DIR/yazelix_init.sh" ]; then
  # shellcheck disable=SC1090
  source "$YAZELIX_BASH_INITIALIZERS_DIR/yazelix_init.sh"
else

# Source individual initializers if they exist and are non-empty.
if [ -f "$YAZELIX_BASH_INITIALIZERS_DIR/starship_init.sh" ] && [ -s "$YAZELIX_BASH_INITIALIZERS_DIR/starship_init.sh" ]; then
  source "$YAZELIX_BASH_INITIALIZERS_DIR/starship_init.sh"
fi

if [ -f "$YAZELIX_BASH_INITIALIZERS_DIR/zoxide_init.sh" ] && [ -s "$YAZELIX_BASH_INITIALIZERS_DIR/zoxide_init.sh" ]; then
  source "$YAZELIX_BASH_INITIALIZERS_DIR/zoxide_init.sh"
fi

# mise_init.sh is generated conditionally by the shellHook.
# Source it if it exists and is non-empty.
if [ -f "$YAZELIX_BASH_INITIALIZERS_DIR/mise_init.sh" ] && [ -s "$YAZELIX_BASH_INITIALIZERS_DIR/mise_init.sh" ]; then
  source "$YAZELIX_BASH_INITIALIZERS_DIR/mise_init.sh"
fi

fi

# Yazelix Aliases for Bash
alias yazelix="nu $YAZELIX_RUNTIME_DIR/nushell/scripts/core/launch_yazelix.nu"
alias lg='lazygit'

# Note: yzx command is defined in ~/.bashrc (via v3 hooks) and is always available

if [ -n "${YAZELIX_CONFIG_DIR:-}" ]; then
  YAZELIX_USER_SHELL_HOOK_DIR="$YAZELIX_CONFIG_DIR/user_configs/shells"
elif [ -n "${YAZELIX_USER_SHELL_HOOK_DIR:-}" ]; then
  YAZELIX_USER_SHELL_HOOK_DIR="$YAZELIX_USER_SHELL_HOOK_DIR"
else
  YAZELIX_USER_SHELL_HOOK_DIR="$HOME/.config/yazelix/user_configs/shells"
fi
YAZELIX_BASH_USER_HOOK="$YAZELIX_USER_SHELL_HOOK_DIR/bash.sh"
if [ -f "$YAZELIX_BASH_USER_HOOK" ] && [ -s "$YAZELIX_BASH_USER_HOOK" ]; then
  # shellcheck disable=SC1090
  source "$YAZELIX_BASH_USER_HOOK"
fi

# Ensure this script doesn't produce output unless it's an error,
# as it's sourced by .bashrc.
